---
title: "Tab 1"
author: "Colin Fay"
date: "9/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pkgload::load_all()
library(dplyr)
session <- new.env()
connect(session)
con <- get_con(session)
library(rworldmap)
library(rworldxtra)
library(tmap)
library(sf)
library(DBI)
```

```{r}
for (i in sort(DBI::dbListTables(con))){
  cli::cat_rule(i)
  print(
    dplyr::tbl(
      con,i
    )
  )
}
```


# Liste des espèces 

```{r}
# golem::add_fct("species", module = "b_first")

#' Get Active species
#'
#' @param session The Shiny Session object
#'
#' @return a tbl with active species
#' @export
#'
#' @examples
# ' if (interactive()){
#   get_species()
# }
get_active_species <- function(
  session = shiny::getDefaultReactiveDomain()
){
  get_con(
    session = session
  ) %>% 
    dplyr::tbl( "species" ) %>% 
    dplyr::filter(active) %>%
    dplyr::collect()
}
get_active_species(
  session = session
)
```

## Conservation status

```{r}
#' Title
#'
#' @param species_id 
#' @param con 
#'
#' @return
#' @export
#'
#' @examples
get_conservation_status <- function(
  species_id, 
  con
){
  sql <-"select species_id, diadesatlas.translate(english_name, 'fr') as fish_name,
array_to_string (
array_agg(
diadesatlas.translate(iucn_classification_code, 'fr') || ': ' || diadesatlas.translate(iucn_level_name,'fr'))
, '<br>')
from diadesatlas.v_iucn
where species_id = ?id
group by species_id, fish_name
;"
  DBI::dbGetQuery(
    con, 
    DBI::sqlInterpolate(con, sql, id = species_id)
  )
}
get_conservation_status(
  25,
  con
)

```


## Tmap code 

### Frontier creation

```{r}
# fontierers on AA and north sea 
worldMap <- getMap(resolution = "high") %>% st_as_sf()

states = c("Portugal", "Spain","France", "United Kingdom", "Ireland", "United Kingdom", "Belgium",
           "Netherlands", "Germany", "Denmark", "Sweden", "Norway", "Poland", "Switzerland","Italy",
           "Luxembourg"  , "Austria", "Finland", 'Greece',
           'Slovenia', 'Hungary' , 'Croatia', 'Slovakia', 'Czech Rep.', 'Bulgaria', 'Romania',
           'Albania', 'Bosnia and Herz.', 'Serbia', 'Montenegro', 'Macedonia', 'Kosovo',
           'Tunisia',  'Libya' ,  'Algeria' , 'Morocco' )

# world_map_crs <- "+proj=eqearth +wktext"
world_map_crs <- "+proj=wintri"
frontiers <- worldMap %>%  
  select(NAME, geometry) %>% 
  filter(NAME %in% states) %>% 
  st_transform(world_map_crs)


bbox <- st_bbox(c(xmin = -17.5, xmax = 19, ymax = 36, ymin = 62), crs = st_crs(4326)) 


tm_shape(frontiers %>% st_transform(world_map_crs), bbox = bbox) + tm_polygons() + 
  tm_graticules(alpha = 0.2) +
  tm_text('NAME', size = 1)


readr::write_rds(frontiers, 'inst/frontiers.rds')
devtools::document()
```

### tmap

```{r}
# golem::add_fct("map", module = "b_first")
#' Title
#'
#' @param species_latin_name 
#' @param spatial_type 
#' @param con 
#' @param yearStart 
#' @param yearEnd 
#' @param dataCatchment 
#' @param catchment_geom 
#' @param dataALL 
#' @param ices_geom 
#'
#' @return
#' @export
#' @import sf
#' @import tmap
#'
#' @examples
tm_draw <- function(
  species_latin_name,
  spatial_type, 
  con,
  yearStart = 2003,
  yearEnd = 2017, 
  dataCatchment, 
  catchment_geom, 
  dataALL, 
  ices_geom
){
  
  #=====================================================================================
  # spatial coverage
  bbox =  st_bbox(c(xmin = -17.5, xmax = 19, ymax = 36, ymin = 62), crs = st_crs(4326)) 
  # ----------------------------------------- country frontier
  
  #--------------------------- data in ocean
  dataOcean <- ices_geom %>% 
    filter(ices_type == spatial_type) %>% 
    inner_join(
      dataALL %>% 
        filter(latin_name == species_latin_name
        ),
      by = c('ices_type', 'gid')
    ) %>% 
    mutate(prevalence = cut(
      nb_occurence, 
      breaks = c(-Inf, 0, 3, 6, 9 ,12, 15),
      labels = c(
        "Not recorded in the period", 
        "[1, 3]",
        "[4, 6]",
        "[7, 9]",
        "[10, 12]",
        "[13, 15]"
      )
    )
    )
  
  
  tm_ocean <- tm_shape(dataOcean,  bbox = bbox) + 
    tm_polygons(
      'prevalence',  
      title = paste0('Annual prevalence in catches at sea \n(', yearStart, '-', yearEnd, ')'),
      palette = "Blues", 
      n = 6
    ) 
  
  # -------------------------------------------------------- data in catchment
  dataContinent <- catchment_geom %>% 
    left_join(
      dataCatchment  %>% 
        filter(
          latin_name == species_latin_name
        ),
      by = "basin_id"
    )
  
  tm_catchmment <- tm_shape(dataContinent) +  
    tm_polygons(
      "abundance_interpretation", 
      title = 'Status in river catchments (1951-2010)',
      palette = "Reds",  
      n = 4
    ) 
  #tm_text('abundance_level_id', size = .5) 
  
  # ------------------------------------------ display the map
  tm_graticules() + 
    tm_ocean  + 
    tm_frontiers +  
    tm_catchmment +
    tm_layout(main.title.fontface = 3,
              main.title.size = 0.8,
              main.title = species_latin_name, # suppress at the end
              legend.position = c("right", "center"),
              legend.outside = TRUE) 
  
}

dataCatchment <-  dbReadTable(
  con,  
  "v_abundance"
) %>% 
  inner_join(
    tribble(~abundance_level_id, ~abundance_interpretation,
            1, 'Not recorded in the period',
            2, 'Occasional vagrants',
            3, 'Functional populations',
            4, 'Abundant functional populations') %>% 
      mutate(abundance_interpretation = factor(abundance_interpretation,
                                               levels = .$abundance_interpretation)), 
    by = "abundance_level_id")

catchment_geom <- st_read(
  con, 
  query =   "SELECT * FROM diadesatlas.v_basin vb"
) %>%
  rmapshaper::ms_simplify()

dataALL <- dbGetQuery(
  con, 
  "SELECT * from diadesatlas.v_species_ices_occurence vsio "
) %>% 
  #tibble() %>% 
  mutate(nb_occurence = as.integer(nb_occurence))

ices_geom <- st_read(
  con, 
  query = "SELECT * FROM diadesatlas.v_ices_geom;"
) %>% 
  # st_transform("+proj=eqearth +wktext") %>%
  st_transform("+proj=wintri") %>%
  rmapshaper::ms_simplify()

tm_draw(
  species_latin_name = "Salmo trutta" ,
  spatial_type = 'rectangle', 
  con = con, 
  dataCatchment = dataCatchment, 
  catchment_geom = catchment_geom, 
  dataALL = dataALL, 
  ices_geom = ices_geom
)

# for (i in get_active_species(session)$latin_name){
#   cli::cat_rule(i)
#   print(
#     tm_draw(
#       species_latin_name = i,
#       spatial_type = 'rectangle', 
#       con = con, 
#       dataCatchment = dataCatchment, 
#       catchment_geom = catchment_geom, 
#       dataALL = dataALL, 
#       ices_geom = ices_geom
#     )
#   )
#   print(
#     tm_draw(
#       species_latin_name = i,
#       spatial_type = 'division', 
#       con = con, 
#       dataCatchment = dataCatchment, 
#       catchment_geom = catchment_geom, 
#       dataALL = dataALL, 
#       ices_geom = ices_geom
#     )  
#   )
#   
# }

```


```{r}
library(shiny)
library(tmap)
session <- new.env()
connect(session)
con <- get_con(session)

container <- function(...){
  tags$div(
    class = "w3-row-padding w3-padding-16 w3-center",
    ...
  )
}


map_ui <- function(id){
  ns <- NS(id)
  container(
    selectInput(
      ns("species"), 
      "Species", 
      choices = get_active_species(
        session
      )$latin_name
    ),
    tmap::tmapOutput(ns("raster"), width = "50%") 
  )
}

map_ <- function(input, output, session){
  ns <- session$ns
  output$raster <- tmap::renderTmap({
    tm_draw(
      species_latin_name = input$species,
      spatial_type = 'rectangle', 
      con = con, 
      dataCatchment = dataCatchment, 
      catchment_geom = catchment_geom, 
      dataALL = dataALL, 
      ices_geom = ices_geom
    )
    
  })
}


ui <- function(request){
  w3css::w3_page(
    map_ui("map_ui")
  )
}

server <- function(
  input, 
  output, 
  session
){
  callModule(map_, "map_ui")
}

shinyApp(ui, server)
```

