---
title: "bb-page1-catch-bycatch"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bb-page1-catch-bycatch}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE # Set to TRUE when data OK for test, but not on GitHub
)
# To compile manually (run in the console directly)
if (FALSE) {
  vignette_name <- "bb-page1-catch-bycatch"
  vignette_file <- paste0(vignette_name, ".Rmd")

  rmarkdown::render(
    input = here::here(file.path("data-raw", vignette_file)),
    output_format = "rmarkdown::html_vignette",
    output_options = list(toc = TRUE),
    output_file = here::here(file.path("vignettes", vignette_file))
  )

  # Add header for title
  lines <- readLines(here::here(file.path("vignettes", vignette_file)))

  cat(
    glue::glue('---
title: ".{vignette_name}."
output: rmarkdown::html_vignette
vignette: >
  %\\VignetteIndexEntry{.{vignette_name}.}
  %\\VignetteEngine{knitr::rmarkdown}
  %\\VignetteEncoding{UTF-8}
---
', .open = ".{", .close = "}."),
    lines,
    sep = "\n",
    file = here::here(file.path("vignettes", vignette_file))
  )
}
```

```{r setup}
# Sys.setenv("POSTGRES_USER" = "diadesatlas_owner")
# Sys.setenv("POSTGRES_PASS" = "thinkrpassword")
pkgload::load_all(here::here())
library(dplyr)
session <- shiny::MockShinySession$new() #new.env()
connect(session)
con <- get_con(session)
library(rworldmap)
library(rworldxtra)
library(tmap)
library(sf)
library(DBI)

library(zeallot)

Sys.setenv(
  "GOLEM_CONFIG_ACTIVE" = "dev"
)
```

# Liste des espèces 

```{r}
get_active_species(
  session = session
)
```

## Conservation status

```{r}
species <- get_active_species(
  session = session
)
for (i in species$species_id) {
  cli::cat_rule(i)
  print(
    get_conservation_status(
      6,
      con
    )
  )
  cli::cat_line()
}
```
## Tmap code 


```{r, eval=FALSE}
dataCatchment <- dbReadTable(
  con,
  "v_abundance"
) %>%
  inner_join(
    tribble(
      ~abundance_level_id, ~abundance_interpretation,
      1, "Not recorded in the period",
      2, "Occasional vagrants",
      3, "Functional populations",
      4, "Abundant functional populations"
    ) %>%
      mutate(abundance_interpretation = factor(abundance_interpretation,
        levels = .$abundance_interpretation
      )),
    by = "abundance_level_id"
  )

catchment_geom <- st_read(  
  con,
  query =   "SELECT * FROM diadesatlas.v_basin vb"
) %>%
  rmapshaper::ms_simplify() %>%
  st_transform("+proj=wintri")

dataALL <- dbGetQuery(
  con,
  "SELECT * from diadesatlas.v_species_ices_occurence vsio "
) %>%
  # tibble() %>%
  mutate(nb_occurence = as.integer(nb_occurence))

ices_geom <- st_read(
  con,
  query = "SELECT * FROM diadesatlas.v_ices_geom;"
) %>%
  # st_transform("+proj=eqearth +wktext") %>%
  st_transform("+proj=wintri") %>%
  rmapshaper::ms_simplify()

dataContinent <- get_data_continent_m(
  session = session
)(
  catchment_geom,
  dataCatchment,
  "Salmo trutta"
)
```

```{r}
c(
  dataCatchment,
  catchment_geom,
  dataALL,
  ices_geom,
  species_list
) %<-% generate_datasets(
  get_con(
    session
  )
)
# options("golem.app.prod" = FALSE)
launch_mongo(session = session)
# NOTE: the species are passed with the latin name in the foreground.
# In the front of the app, the user will have to select an english/french name
tm_draw(
  species_latin_name = "Salmo trutta",
  spatial_type = "rectangle",
  con = con,
  dataCatchment = dataCatchment,
  catchment_geom = catchment_geom,
  dataALL = dataALL,
  ices_geom = ices_geom,
  session = session
)

tm_draw(
  species_latin_name = "Salmo trutta",
  spatial_type = "division",
  con = con,
  dataCatchment = dataCatchment,
  catchment_geom = catchment_geom,
  dataALL = dataALL,
  ices_geom = ices_geom,
  session = session
)

tm_draw(
  species_latin_name = "Chelon ramada",
  spatial_type = "rectangle",
  con = con,
  dataCatchment = dataCatchment,
  catchment_geom = catchment_geom,
  dataALL = dataALL,
  ices_geom = ices_geom,
  session = session
)

tm_draw(
  species_latin_name = "Chelon ramada",
  spatial_type = "division",
  con = con,
  dataCatchment = dataCatchment,
  catchment_geom = catchment_geom,
  dataALL = dataALL,
  ices_geom = ices_geom,
  session = session
)
```

## Disconnect db
```{r}
DBI::dbDisconnect(con)
```

