---
title: "bd-page3-climate-change"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bd-page3-climate-change}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE # Set to TRUE when data OK for test, but not on GitHub
)
# To compile manually (run in the console directly)
if (FALSE) {
  vignette_name <- "bd-page3-climate-change"
  vignette_file <- paste0(vignette_name, ".Rmd")

  rmarkdown::render(
    input = here::here(file.path("data-raw", vignette_file)),
    output_format = "rmarkdown::html_vignette",
    output_options = list(toc = TRUE),
    output_file = here::here(file.path("vignettes", vignette_file))
  )

  # Add header for title
  lines <- readLines(here::here(file.path("vignettes", vignette_file)))

  cat(
    glue::glue('---
title: ".{vignette_name}."
output: rmarkdown::html_vignette
vignette: >
  %\\VignetteIndexEntry{.{vignette_name}.}
  %\\VignetteEngine{knitr::rmarkdown}
  %\\VignetteEncoding{UTF-8}
---
', .open = ".{", .close = "}."),
    lines,
    sep = "\n",
    file = here::here(file.path("vignettes", vignette_file))
  )
}
```

```{r setup}
library(diades.atlas)
# renv::install("dm")
# library(dm)
library(dplyr)
library(leaflet)
library(ggplot2)
```

### Connect to database

Do not forget to set environment variables in .Renviron
```{r}
pkgload::load_all(attach_testthat = FALSE)
session <- new.env()
connect(session)
library(leaflet)
library(shiny)
library(tmap)
library(dbplyr)
library(dplyr)
input <- new.env()
c(
  dataCatchment,
  catchment_geom,
  dataALL,
  ices_geom,
  species_list
) %<-% generate_datasets(
  get_con(
    session
  )
)

species_id <- species_list[species_list$latin_name == "alosa-fallax", "species_id"]

scenario <- "rcp85"
date <- c(1970, 2010)

hybrid_model_result <- tbl(get_con(session), "hybrid_model_result")

# get_hybrid_model() in R/mod_c_second_fct_query_and_plot.R
model_res <- get_hybrid_model(
  species_id = 6,
  scenario = "rcp85",
  # date = c(1970, 2010),
  session = session
)

tbl(
  get_con(session),
  "hybrid_model_result"
) %>% distinct(species_id)

# Available_bv
bv_ids <- sort(
  unique(model_res$basin_id)
)

get_bv_geoms <- function(bv_ids,
                         lg,
                         session = shiny::getDefaultReactiveDomain()) {
  res <- sf::st_read(
    get_con(session),
    query = sprintf(
      "select basin_id, verysimplified_geom, ccm_name from basin_outlet where basin_id IN %s",
      dbplyr::translate_sql(!!bv_ids)
    )
  )
  basin <- tbl(get_con(session), "basin") %>%
    filter(basin_id %in% !!res$basin_id) %>%
    mutate(basin_name = diadesatlas.translate(basin_name, !!lg)) %>%
    select(basin_id, basin_name) %>%
    collect()
  
  res %>%
  left_join(basin, by = "basin_id")
}

bv_df <- get_bv_geoms(
  bv_ids,
  'fr',
  session
)
year <- 1951
draw_bv_leaflet <- function(bv_df,
                            model_res,
                            year) {
  bv_df <- left_join(
    bv_df,
    filter(model_res, year == !!year),
    by = "basin_id"
  )
  factpal <- colorNumeric(
    palette = "YlOrRd",
    domain = bv_df$nit,
    reverse = FALSE
  )

  leaflet() %>%
    addTiles() %>%
    addPolygons(data = bv_df, 
                layerId = ~basin_id, 
                fillColor = ~ factpal(nit),
                color = "#525252",
                weight = 1,
                label = ~basin_name,
                opacity = 0.8,
                fillOpacity = 0.6
                ) %>% 
      addLegend(data = bv_df,
                pal = factpal, values = ~nit,
                title = "NIT",
                opacity = 0.6)
}




# plot hsi nit ----

selected_bv <- 385
selected_year <- 2002
plot_hsi_nit <- function(model_res,
                         selected_year,
                         selected_bv) {
  model_res_filtered <- model_res %>%
    filter(
      basin_id == selected_bv
    )
  hsi <- ggplot(
    model_res_filtered,
    aes(year, hsi)
  ) +
    geom_line() +
    geom_vline(xintercept = selected_year, color = "red")
  nit <- ggplot(
    model_res_filtered,
    aes(year, nit)
  ) +
    geom_line() +
    geom_vline(xintercept = selected_year, color = "red")
  patchwork:::`/.ggplot`(
    hsi, nit
  )
}

# Plot leaflet
bv_df <- get_bv_geoms(
  bv_ids,
  'fr',
  session
)
draw_bv_leaflet(bv_df, model_res, 1976)
```

## Test separate shiny module

```{r, eval=FALSE}
ui <- function(request) {
  tagList(
    leaflet::leafletOutput("plot")
  )
}

server <- function(input,
                   output,
                   session) {
  output$plot <- leaflet::renderLeaflet({
    draw_bv_leaflet(bv_df, model_res, 1976)
  })

  observeEvent(input$plot_shape_click, { # update the location selectInput on map clicks
    print(input$plot_shape_click)
  })
}

shinyApp(ui, server)
```


### Stop connection

```{r}
# DBI::dbDisconnect(con)
DBI::dbDisconnect(session$userData$con)
```
