---
title: "be-page4-future"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{be-page4-future}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = TRUE # Set to TRUE when data OK for test, but not on GitHub
)
# To compile manually : See README
```

```{r setup, message=FALSE}
# library(diades.atlas)
pkgload::load_all(here::here())
library(dplyr)
library(leaflet)
library(ggplot2)
```

### Connect to database

Do not forget to set environment variables in .Renviron
```{r}
# Connect to database
conn_eurodiad <- connect()

# Listtables
# sort(DBI::dbListTables(conn_eurodiad))
# DBI::dbListObjects(conn_eurodiad)
```

## Prepare Data

Queries from preparation_atlas_simulation.R

```{r}
data_simulation <- get_data_simulation(conn_eurodiad)
data_catchment <- data_simulation[["data_catchment"]]
data_catchment
data_simulation[["outlet_distance"]]
hydiad_parameter <- data_simulation[["hydiad_parameter"]]
hydiad_parameter
data_hsi_nmax <- data_simulation[["data_hsi_nmax"]]
data_hsi_nmax
reference_results <- data_simulation[["reference_results"]]
data_simulation[["data_ni0"]]
catchment_surface <- data_simulation[["catchment_surface"]]
```

## Prepare data frame of simulation

- Use anthropogenic mortality from the Shiny interface

```{r}
session <- shiny::MockShinySession$new()
session$userData$con <- conn_eurodiad
input <- list()
datasets <- generate_datasets(con = conn_eurodiad)
lang <- "fr"

# Generate all inputs as in the Shiny application
countries <- datasets[["countries_mortalities_list"]]

mortalities <- tibble::tibble(
  # country = golem::get_golem_options('countries_mortalities_list'),
  country = datasets[["countries_mortalities_list"]],
  yearsimubegin = 
    case_when(
      country == "France" ~ -log(.5),
      # country == "France" ~ -5,
      TRUE ~ 0
    ),
  # rep(-log(.5), length(datasets[["countries_mortalities_list"]])),
  yearsimuend = 
    case_when(
      country == "France" ~ -log(.75),
      TRUE ~ 0
    )
  # rep(-log(.75), length(datasets[["countries_mortalities_list"]]))
)

mortalities

scenario <- "rcp85"

# # build from sliders in interface 
# expand grid using full_join
anthropogenic_mortality <- expand_anthropogenic_mortality(
  data_hsi_nmax, mortalities)

selected_latin_name = "Alosa alosa"

# TODO - In Shiny only - 
# Use https://shiny.rstudio.com/articles/progress.html
shiny::withProgress(
  message = 'Making Simu', value = 0, 
  session = session, {

    results <- runSimulation(
      selected_latin_name, 
      data_simulation[["hydiad_parameter"]], # 11 rows
      # Smaller for example
      anthropogenic_mortality, # 1800 rows
      data_simulation[["catchment_surface"]], # 134 rows
      data_simulation[["data_hsi_nmax"]], # 663300 rows
      data_simulation[["data_ni0"]], # 4422 rows
      data_simulation[["outlet_distance"]], # 18225 rows
      # Add scenario
      scenario = scenario,
      verbose = FALSE
    )
  })

# [1] "cnrmcm5"    "csiromk360"
# [3] "noresm1me" 

# Les 5 premières lignes des sous-listes
# results %>% purrr::map(~purrr::map(.x, head))
```

### Graphs for Nit

```{r, out.width="100%", fig.width=6}
# graphics ----
Nit_list <- get_model_nit(results) 

basin <- 'Garonne'

# Plot Nit predictions
model_res_filtered <- nit_feature_species(
  Nit_list = Nit_list,
  reference_results = reference_results %>%
    filter(climatic_scenario == scenario),
  selected_latin_name = selected_latin_name)
  
# same function as for Page 3
model_res_filtered %>% 
  filter(basin_name == basin) %>% 
  # filter(source == "reference") %>% 
  plot_nit(selected_year = 2073,
           lg = "fr",
           withNitStandardisation = FALSE,
           with_colour_source = "source")

```

## Leaflet

```{r}
loco <- list()
loco$model_res <- model_res_filtered %>% 
  filter(source == "simul") %>% 
  left_join(data_simulation[["data_catchment"]] %>% collect(),
            by = "basin_name")

loco$bv_df <- get_bv_geoms(
  unique(loco$model_res$basin_id),
  lg = "fr", #r$lg,
  session
)

draw_bv_leaflet(
          bv_df = loco$bv_df,
          model_res = loco$model_res,
          year = 2100
        )
```


### Stop connection

```{r}
DBI::dbDisconnect(conn_eurodiad)
```
