---
title: "aa-data-exploration-and-preparation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{aa-data-exploration-and-preparation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>aa-partie-exploration-des-donnees</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">aa-partie-exploration-des-donnees</h1>


<div id="TOC">
<ul>
<li><a href="#data-exploration" id="toc-data-exploration">Data
exploration</a>
<ul>
<li><a href="#connect-to-database" id="toc-connect-to-database">Connect
to database</a></li>
<li><a href="#create-connection" id="toc-create-connection">Create
connection</a></li>
<li><a href="#function-to-collect-data" id="toc-function-to-collect-data">Function to collect data</a></li>
</ul></li>
<li><a href="#prepare-data-for-home-page" id="toc-prepare-data-for-home-page">Prepare data for Home page</a>
<ul>
<li><a href="#prepare-json-files" id="toc-prepare-json-files">Prepare
json files</a></li>
<li><a href="#stop-connection" id="toc-stop-connection">Stop
connection</a></li>
</ul></li>
</ul>
</div>

<p>This vignette explores the tables in the database and ensures that R
has access to the tables. It also transforms the data in json.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(diades.atlas)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># renv::install(&quot;dm&quot;)</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># library(dm)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<div id="data-exploration" class="section level2">
<h2>Data exploration</h2>
<div id="connect-to-database" class="section level3">
<h3>Connect to database</h3>
<p>Do not forget to set environment variables in .Renviron</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>postgis_host <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_HOST&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>postgis_user <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_USER&quot;</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>postgis_password <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_PASSWORD&quot;</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> DBI<span class="sc">::</span><span class="fu">dbConnect</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  RPostgres<span class="sc">::</span><span class="fu">Postgres</span>(),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">host =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_HOST&quot;</span>, diades.atlas<span class="sc">:::</span><span class="fu">get_golem_config</span>(<span class="st">&quot;POSTGRES_HOST&quot;</span>)),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">dbname =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_DBNAME&quot;</span>, diades.atlas<span class="sc">:::</span><span class="fu">get_golem_config</span>(<span class="st">&quot;POSTGRES_DBNAME&quot;</span>)),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">port =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_PORT&quot;</span>, diades.atlas<span class="sc">:::</span><span class="fu">get_golem_config</span>(<span class="st">&quot;POSTGRES_PORT&quot;</span>)),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">user =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_USER&quot;</span>, <span class="st">&quot;diadesatlas_r&quot;</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">password =</span> <span class="fu">Sys.getenv</span>(<span class="st">&quot;POSTGRES_PASS&quot;</span>, <span class="st">&quot;diadesPassword&quot;</span>),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">options =</span> <span class="st">&quot;-c search_path=diadesatlas&quot;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Listtables</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># DBI::dbListTables(con)</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># DBI::dbListObjects(con)</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the names of all the tables in the schema</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>all_schemas <span class="ot">&lt;-</span> DBI<span class="sc">::</span><span class="fu">dbGetQuery</span>(con, <span class="st">&quot;SELECT table_name FROM information_schema.tables WHERE table_schema=&#39;diadesatlas&#39;&quot;</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>all_schemas</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  table_name</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1           outlet_distance</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2           hydiadparameter</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            basin_location</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4           ices_rectangle2</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5             ices_division</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6                     cices</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7                 abundance</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8               v_abundance</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9                 dbversion</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                   v_iucn</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 11          abundance_level</span></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 12      v_hybrid_model_mavg</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 13   v_ecosystemic_services</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 14              v_occurence</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 15                  v_basin</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 16 v_species_ices_occurence</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 17           v_hybrid_model</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 18             species_iucn</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 19                ices_area</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 20           ices_rectangle</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 21      iucn_classification</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 22               iucn_level</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 23         species_division</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 24        species_rectangle</span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 25              v_ices_geom</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 26                  esvalue</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 27                   locale</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 28      hybrid_model_result</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 29                casestudy</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 30     ecosystemic_services</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 31                    basin</span></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 32             basin_outlet</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 33          casestudy_basin</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 34           climatic_model</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 35                  species</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 36                 category</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 37              subcategory</span></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 38            v_maxvalue_es</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 39                lang85_85</span></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 40               ices_grass</span></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the head of all</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> all_schemas<span class="sc">$</span>table_name) {</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, i)))</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;outlet_distance&quot;&gt; [?? x 3]</span></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    departure arrival distance</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        &lt;int&gt;   &lt;int&gt;    &lt;dbl&gt;</span></span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1         1       1       0 </span></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2         1       3    1279.</span></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3         1     387    2458.</span></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4         1     358    2015.</span></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5         1     359    1382.</span></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6         1     290    1491.</span></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7         1      14     662.</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8         1      15     173.</span></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9         1      16     965.</span></span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10         1     385    2259.</span></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;hydiadparameter&quot;&gt; [?? x 16]</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_id   Dmax   lambda     r AgeFirstMat nbCohorts  gamma DistMean     alpha  beta   Mdisp DistMax withAllee</span></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         &lt;int&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;     &lt;int&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;lgl&gt;    </span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1          6  7.11  0.0931     1.3         5           3 0.173     40.5  0.444     0.417 1.90e-2   256.  TRUE     </span></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2          8  4.07  0.442      1.3         3           3 0.145     24.0  0.549     0.418 3.69e-2   151.  TRUE     </span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3         18  0.714 0.193      1.3         5           3 0.366     10    0.216     0.706 3.81e-2    41.2 TRUE     </span></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4         21  1.17  0.136      1.3         8           3 0.628     83.2  0.0180    0.869 4.88e-3   300.  TRUE     </span></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5         25  0.496 0.270      1.3         3           3 0.0605    20.5  0.380     0.496 3.57e-2   111.  TRUE     </span></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6         26 11.5   0.00851    1.3         3.5         3 0.0828    25.4  0.0376    0.931 2.92e-2    88.0 TRUE     </span></span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7          4  0.106 0.0472     1.3        11           3 0.0865   464.   0.000110  1.35  4.28e-4  1323.  TRUE     </span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8         20 46.2   0.00143    1.3         2           3 0.109      2.42 0.904     0.556 3.98e-1    11.9 TRUE     </span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9         13 35.9   0          1.3        12           3 0.253    170.   0.0000204 1.85  4.67e-3   413.  TRUE     </span></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10         19 50.3   0.000432   1.3         3.5         3 0.210     39.8  0.000301  1.84  8.32e-3   100   TRUE     </span></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 3 more variables: withNatalStray &lt;lgl&gt;, usePresence &lt;lgl&gt;, Sdisp &lt;dbl&gt;</span></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;basin_location&quot;&gt; [?? x 6]</span></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_id basin_name    surface_area basin_geom                basin_geom_simplified          outlet_geom     </span></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt; &lt;pq_gmtry&gt;                &lt;pq_gmtry&gt;                     &lt;pq_gmtry&gt;      </span></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1        1 Aa                   1287. 0106000020E6100000010000… 0103000020E610000001000000670… 0101000020E6100…</span></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2        2 Adige               12417. 0106000020E6100000010000… 0103000020E610000001000000440… 0101000020E6100…</span></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3        5 Aksu                18175. 0106000020E6100000020000… 0103000020E6100000010000006D0… 0101000020E6100…</span></span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4        8 Angermanalven       31815. 0106000020E6100000080000… 0103000020E610000001000000710… 0101000020E6100…</span></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5       11 Asi                 57018. 0106000020E6100000010000… 0103000020E610000001000000AB0… 0101000020E6100…</span></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6       18 Axios_Vardar        24397. 0106000020E6100000040000… 0103000020E610000001000000080… 0101000020E6100…</span></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7      303 Arachthos            2441. 0106000020E6100000010000… 0103000020E610000001000000AD0… 0101000020E6100…</span></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8      306 Evrotas              1770. 0106000020E6100000010000… 0103000020E610000001000000700… 0101000020E6100…</span></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9      366 Oka                   143. 0106000020E6100000010000… 0103000020E6100000010000001C0… 0101000020E6100…</span></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10       44 Don                429400. 0106000020E6100000020000… 0103000020E610000001000000E70… 0101000020E6100…</span></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ices_rectangle2&quot;&gt; [?? x 5]</span></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ices_type   gid icesname geom                                    exterior_geom                               </span></span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;    &lt;pq_gmtry&gt;                              &lt;pq_gmtry&gt;                                  </span></span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 rectangle  1846 01D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 rectangle  1847 02D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 rectangle  1848 03D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 rectangle  1849 04D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 rectangle  1850 05D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 rectangle  1851 06D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 rectangle  1852 07D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 rectangle  1853 08D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 rectangle  1854 09D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 rectangle  1855 10D2     0106000020E610000001000000010300000001… 0103000020E610000001000000050000001092FFFFF…</span></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ices_division&quot;&gt; [?? x 5]</span></span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ices_type   gid icesname simplified_geom                             exterior_geom                           </span></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;    &lt;pq_gmtry&gt;                                  &lt;pq_gmtry&gt;                              </span></span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 division     72 27.3.a   0103000020E610000052040000A8220000146DB504… 0103000020E610000001000000A8220000146DB…</span></span>
<span id="cb2-132"><a href="#cb2-132" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 division     10 27.4.a   0106000020E6100000030000000103000000800A00… 0103000020E6100000010000001C30000075308…</span></span>
<span id="cb2-133"><a href="#cb2-133" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 division      8 27.4.b   0103000020E610000068000000DA160000948116A9… 0103000020E610000001000000DA16000094811…</span></span>
<span id="cb2-134"><a href="#cb2-134" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 division      7 27.4.c   0103000020E61000006A00000055100000473D2BA7… 0103000020E61000000100000055100000473D2…</span></span>
<span id="cb2-135"><a href="#cb2-135" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 division     27 27.6.a   0103000020E61000009C0200000B240000F7260400… 0103000020E6100000010000000B240000F7260…</span></span>
<span id="cb2-136"><a href="#cb2-136" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 division     78 27.6.b   0103000020E610000002000000050000002BD00000… 0103000020E610000001000000050000002BD00…</span></span>
<span id="cb2-137"><a href="#cb2-137" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 division     48 27.7.a   0106000020E6100000040000000103000000010000… 0103000020E6100000010000007D6300008C7B6…</span></span>
<span id="cb2-138"><a href="#cb2-138" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 division     42 27.7.b   0103000020E61000000F01000081130000A17EB9EA… 0103000020E61000000100000081130000A17EB…</span></span>
<span id="cb2-139"><a href="#cb2-139" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 division     79 27.7.c   0103000020E610000001000000050000002BD00000… 0103000020E610000001000000050000002BD00…</span></span>
<span id="cb2-140"><a href="#cb2-140" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 division     47 27.7.d   0106000020E6100000020000000103000000150000… 0103000020E61000000100000034070000FCF03…</span></span>
<span id="cb2-141"><a href="#cb2-141" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-142"><a href="#cb2-142" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;cices&quot;&gt; [?? x 4]</span></span>
<span id="cb2-143"><a href="#cb2-143" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-144"><a href="#cb2-144" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    cices_id mea                   cices                                           expert_knowledge              </span></span>
<span id="cb2-145"><a href="#cb2-145" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;int&gt; &lt;chr&gt;                 &lt;chr&gt;                                           &lt;chr&gt;                         </span></span>
<span id="cb2-146"><a href="#cb2-146" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1        1 Provisioning services &quot;Biomass (wild animals and their outputs)&quot;      Food provision                </span></span>
<span id="cb2-147"><a href="#cb2-147" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2        2 Provisioning services &quot;Biomass (wild animals and their outputs)&quot;      Option value (Leather provisi…</span></span>
<span id="cb2-148"><a href="#cb2-148" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3        3 Provisioning services &quot;Biomass (wild animals and their outputs)&quot;      Option value (Molecule provis…</span></span>
<span id="cb2-149"><a href="#cb2-149" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4        4 Cultural services     &quot;Physical and experiential interactions with n… Recreation sport fishing      </span></span>
<span id="cb2-150"><a href="#cb2-150" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5        5 Cultural services     &quot;Physical and experiential interactions with n… Sport fishing competitions    </span></span>
<span id="cb2-151"><a href="#cb2-151" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6        6 Cultural services     &quot;Physical and experiential interactions with n… Option value (fishing competi…</span></span>
<span id="cb2-152"><a href="#cb2-152" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7        7 Cultural services     &quot;Spiritual, symbolic, and other interactions w… Spiritual experience (includi…</span></span>
<span id="cb2-153"><a href="#cb2-153" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8        8 Cultural services     &quot;Intellectual and representative interactions … Gastronomy around species and…</span></span>
<span id="cb2-154"><a href="#cb2-154" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9        9 Cultural services     &quot;Intellectual and representative interactions … Gastronomic festival or events</span></span>
<span id="cb2-155"><a href="#cb2-155" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10       10 Cultural services     &quot;Intellectual and representative interactions … Art and folklore              </span></span>
<span id="cb2-156"><a href="#cb2-156" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-157"><a href="#cb2-157" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;abundance&quot;&gt; [?? x 14]</span></span>
<span id="cb2-158"><a href="#cb2-158" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-159"><a href="#cb2-159" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_id abundance_id presence_absence year_from year_to period_comment abundance_migrator… abundance_reside…</span></span>
<span id="cb2-160"><a href="#cb2-160" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;int&gt;        &lt;int&gt;            &lt;int&gt;     &lt;int&gt;   &lt;int&gt; &lt;chr&gt;          &lt;chr&gt;               &lt;chr&gt;            </span></span>
<span id="cb2-161"><a href="#cb2-161" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1        1            1                0      1951    2010 2000           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-162"><a href="#cb2-162" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2        1            2                0      1851    1950 1900           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-163"><a href="#cb2-163" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3        3            5                0      1951    2010 2000           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-164"><a href="#cb2-164" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4        3            6                0      1851    1950 1900           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-165"><a href="#cb2-165" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5       14           29                0      1951    2010 2000           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-166"><a href="#cb2-166" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6       14           30                0      1851    1950 1900           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-167"><a href="#cb2-167" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7       15           31                0      1951    2010 2000           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-168"><a href="#cb2-168" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8       15           32                0      1851    1950 1900           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-169"><a href="#cb2-169" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9       16           33                0      1951    2010 2000           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-170"><a href="#cb2-170" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10       16           34                0      1851    1950 1900           &lt;NA&gt;                &lt;NA&gt;             </span></span>
<span id="cb2-171"><a href="#cb2-171" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 6 more variables: bibliography &lt;chr&gt;, ecoregion_code &lt;int&gt;, ecoregion_name &lt;chr&gt;,</span></span>
<span id="cb2-172"><a href="#cb2-172" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   abundance_migratory_id &lt;int&gt;, abundance_resident_id &lt;int&gt;, species_id &lt;int&gt;</span></span>
<span id="cb2-173"><a href="#cb2-173" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_abundance&quot;&gt; [?? x 13]</span></span>
<span id="cb2-174"><a href="#cb2-174" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-175"><a href="#cb2-175" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_id abundance_id abundance_level_id species_id year_from year_to basin_name latin_name        simplified_name</span></span>
<span id="cb2-176"><a href="#cb2-176" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;int&gt;        &lt;int&gt;              &lt;int&gt;      &lt;int&gt;     &lt;int&gt;   &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;             &lt;chr&gt;          </span></span>
<span id="cb2-177"><a href="#cb2-177" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1      179        26667                  3          8      2011      NA Vire       Alosa fallax      A. fallax      </span></span>
<span id="cb2-178"><a href="#cb2-178" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2      188        26668                  1          8      2011      NA Yser       Alosa fallax      A. fallax      </span></span>
<span id="cb2-179"><a href="#cb2-179" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3       69        25726                  1          4      2011      NA Gudenaa    Acipenser sturio  A. sturio      </span></span>
<span id="cb2-180"><a href="#cb2-180" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4      174        25727                  1          4      2011      NA Vida       Acipenser sturio  A. sturio      </span></span>
<span id="cb2-181"><a href="#cb2-181" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5       69        25730                  1          6      2011      NA Gudenaa    Alosa alosa       A. alosa       </span></span>
<span id="cb2-182"><a href="#cb2-182" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6      174        25731                  1          6      2011      NA Vida       Alosa alosa       A. alosa       </span></span>
<span id="cb2-183"><a href="#cb2-183" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7       69        25734                  2          8      2011      NA Gudenaa    Alosa fallax      A. fallax      </span></span>
<span id="cb2-184"><a href="#cb2-184" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8      174        25735                 NA          8      2011      NA Vida       Alosa fallax      A. fallax      </span></span>
<span id="cb2-185"><a href="#cb2-185" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9       69        25744                  3         13      2011      NA Gudenaa    Anguilla anguilla A. anguilla    </span></span>
<span id="cb2-186"><a href="#cb2-186" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10      174        25745                  3         13      2011      NA Vida       Anguilla anguilla A. anguilla    </span></span>
<span id="cb2-187"><a href="#cb2-187" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 4 more variables: fish_name &lt;chr&gt;, abundance_level_name &lt;chr&gt;,</span></span>
<span id="cb2-188"><a href="#cb2-188" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   abundance_level_interpretation &lt;chr&gt;, abundance_level_interpretation_short &lt;chr&gt;</span></span>
<span id="cb2-189"><a href="#cb2-189" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;dbversion&quot;&gt; [?? x 3]</span></span>
<span id="cb2-190"><a href="#cb2-190" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-191"><a href="#cb2-191" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   dbversion_id dbversion_number dbversion_date     </span></span>
<span id="cb2-192"><a href="#cb2-192" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          &lt;int&gt; &lt;chr&gt;            &lt;dttm&gt;             </span></span>
<span id="cb2-193"><a href="#cb2-193" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1            1 1.0.0            2022-05-16 00:00:00</span></span>
<span id="cb2-194"><a href="#cb2-194" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2            2 1.0.1            2022-06-09 17:56:44</span></span>
<span id="cb2-195"><a href="#cb2-195" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            3 1.0.2            2023-02-07 15:08:54</span></span>
<span id="cb2-196"><a href="#cb2-196" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_iucn&quot;&gt; [?? x 7]</span></span>
<span id="cb2-197"><a href="#cb2-197" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-198"><a href="#cb2-198" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_id latin_name           simplified_name english_name iucn_classifica… iucn_level_code iucn_level_name</span></span>
<span id="cb2-199"><a href="#cb2-199" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         &lt;int&gt; &lt;chr&gt;                &lt;chr&gt;           &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;           &lt;chr&gt;          </span></span>
<span id="cb2-200"><a href="#cb2-200" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1          6 Alosa alosa          A. alosa        Allis shad   IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-201"><a href="#cb2-201" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2         22 Platichthys flesus   P. flesus       European fl… IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-202"><a href="#cb2-202" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3          8 Alosa fallax         A. fallax       Twaite shad  IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-203"><a href="#cb2-203" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4         13 Anguilla anguilla    A. anguilla     European eel IUCN_Europe      CR              Critically End…</span></span>
<span id="cb2-204"><a href="#cb2-204" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5         18 Lampetra fluviatilis L. fluviatilis  River lampr… IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-205"><a href="#cb2-205" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6         21 Petromyzon marinus   P. marinus      Sea lamprey  IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-206"><a href="#cb2-206" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7         25 Salmo salar          S. salar        Atlantic sa… IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-207"><a href="#cb2-207" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8         26 Salmo trutta         S. trutta       Sea trout    IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-208"><a href="#cb2-208" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9         20 Osmerus eperlanus    O. eperlanus    European sm… IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-209"><a href="#cb2-209" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10         19 Chelon ramada        C. ramada       Thinlip gre… IUCN_Europe      LC              Least Concern  </span></span>
<span id="cb2-210"><a href="#cb2-210" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-211"><a href="#cb2-211" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;abundance_level&quot;&gt; [?? x 4]</span></span>
<span id="cb2-212"><a href="#cb2-212" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-213"><a href="#cb2-213" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   abundance_level_id abundance_level_name abundance_level_interpretation                 abundance_level_interp…</span></span>
<span id="cb2-214"><a href="#cb2-214" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                &lt;int&gt; &lt;chr&gt;                &lt;chr&gt;                                          &lt;chr&gt;                  </span></span>
<span id="cb2-215"><a href="#cb2-215" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1                  1 absent               The species was never recorded in the catchme… Not recorded in the pe…</span></span>
<span id="cb2-216"><a href="#cb2-216" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2                  2 rare                 Occasional vagrants were recorded in the catc… Occasional vagrants    </span></span>
<span id="cb2-217"><a href="#cb2-217" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3                  3 common               Functional populations were present in the ca… Functional populations </span></span>
<span id="cb2-218"><a href="#cb2-218" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4                  4 abundant             Functional populations were present in and nu… Abundant functional po…</span></span>
<span id="cb2-219"><a href="#cb2-219" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_hybrid_model_mavg&quot;&gt; [?? x 14]</span></span>
<span id="cb2-220"><a href="#cb2-220" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-221"><a href="#cb2-221" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    latin_name    basin_name climatic_scenar… species_id basin_id  year nit_min nit_mean nit_max hsi_min hsi_mean</span></span>
<span id="cb2-222"><a href="#cb2-222" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;         &lt;chr&gt;      &lt;chr&gt;                 &lt;int&gt;    &lt;int&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;</span></span>
<span id="cb2-223"><a href="#cb2-223" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 Acipenser st… Aa         rcp45                     4        1  1951    8.71    15.2    27.5   0.0677   0.118 </span></span>
<span id="cb2-224"><a href="#cb2-224" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 Acipenser st… Aa         rcp45                     4        1  1952    9.48    11.4    14.9   0.0737   0.0889</span></span>
<span id="cb2-225"><a href="#cb2-225" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 Acipenser st… Aa         rcp45                     4        1  1953   13.2     14.1    14.9   0.103    0.110 </span></span>
<span id="cb2-226"><a href="#cb2-226" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 Acipenser st… Aa         rcp45                     4        1  1954   12.3     13.9    15.6   0.0958   0.108 </span></span>
<span id="cb2-227"><a href="#cb2-227" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 Acipenser st… Aa         rcp45                     4        1  1955    8.12    17.4    27.5   0.0631   0.135 </span></span>
<span id="cb2-228"><a href="#cb2-228" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 Acipenser st… Aa         rcp45                     4        1  1956    8.75    11.2    15.7   0.0680   0.0869</span></span>
<span id="cb2-229"><a href="#cb2-229" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 Acipenser st… Aa         rcp45                     4        1  1957    8.75    13.1    17.3   0.0680   0.102 </span></span>
<span id="cb2-230"><a href="#cb2-230" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 Acipenser st… Aa         rcp45                     4        1  1958    9.10    10.6    13.3   0.0707   0.0826</span></span>
<span id="cb2-231"><a href="#cb2-231" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 Acipenser st… Aa         rcp45                     4        1  1959    4.52     7.57    9.10  0.0352   0.0589</span></span>
<span id="cb2-232"><a href="#cb2-232" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 Acipenser st… Aa         rcp45                     4        1  1960    9.93    15.5    20.5   0.0772   0.120 </span></span>
<span id="cb2-233"><a href="#cb2-233" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 3 more variables: hsi_max &lt;dbl&gt;, nit_movingavg &lt;dbl&gt;, hsi_movingavg &lt;dbl&gt;</span></span>
<span id="cb2-234"><a href="#cb2-234" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_ecosystemic_services&quot;&gt; [?? x 14]</span></span>
<span id="cb2-235"><a href="#cb2-235" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-236"><a href="#cb2-236" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    category_id casestudy_id species_id subcategory_id esvalue_id subcategory_name      category_name  latin_name</span></span>
<span id="cb2-237"><a href="#cb2-237" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          &lt;int&gt;        &lt;int&gt;      &lt;int&gt;          &lt;int&gt;      &lt;int&gt; &lt;chr&gt;                 &lt;chr&gt;          &lt;chr&gt;     </span></span>
<span id="cb2-238"><a href="#cb2-238" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1           2            9         21             99          0 ALL EXISTING SUBCATE… Provisionning… Petromyzo…</span></span>
<span id="cb2-239"><a href="#cb2-239" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2           1            9         19             99          0 ALL EXISTING SUBCATE… Cultural serv… Chelon ra…</span></span>
<span id="cb2-240"><a href="#cb2-240" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3           3            5         20              3         -1 Redistribution of nu… Regulating se… Osmerus e…</span></span>
<span id="cb2-241"><a href="#cb2-241" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4           1            4          4              7          0 Natural heritage and… Cultural serv… Acipenser…</span></span>
<span id="cb2-242"><a href="#cb2-242" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5           2            7         20              1          0 Food provision from … Provisionning… Osmerus e…</span></span>
<span id="cb2-243"><a href="#cb2-243" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6           1            9          6             99          1 ALL EXISTING SUBCATE… Cultural serv… Alosa alo…</span></span>
<span id="cb2-244"><a href="#cb2-244" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7           1            1         19              8          2 Recreation sport fis… Cultural serv… Chelon ra…</span></span>
<span id="cb2-245"><a href="#cb2-245" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8           2            3          4             99          0 ALL EXISTING SUBCATE… Provisionning… Acipenser…</span></span>
<span id="cb2-246"><a href="#cb2-246" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9           2            5         26              2         -1 Option value associa… Provisionning… Salmo tru…</span></span>
<span id="cb2-247"><a href="#cb2-247" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10           2            8         20             99          0 ALL EXISTING SUBCATE… Provisionning… Osmerus e…</span></span>
<span id="cb2-248"><a href="#cb2-248" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 6 more variables: simplified_name &lt;chr&gt;, fish_name &lt;chr&gt;, casestudy_name &lt;chr&gt;,</span></span>
<span id="cb2-249"><a href="#cb2-249" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   esvalue_code &lt;chr&gt;, esvalue_name &lt;chr&gt;, sortorder &lt;int&gt;</span></span>
<span id="cb2-250"><a href="#cb2-250" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_occurence&quot;&gt; [?? x 8]</span></span>
<span id="cb2-251"><a href="#cb2-251" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-252"><a href="#cb2-252" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ices_type species_id   gid fish_name           latin_name         simplified_name icesname nb_occurence</span></span>
<span id="cb2-253"><a href="#cb2-253" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;          &lt;int&gt; &lt;int&gt; &lt;chr&gt;               &lt;chr&gt;              &lt;chr&gt;           &lt;chr&gt;         &lt;int64&gt;</span></span>
<span id="cb2-254"><a href="#cb2-254" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 rectangle          8  3329 Twaite shad         Alosa fallax       A. fallax       28E8                7</span></span>
<span id="cb2-255"><a href="#cb2-255" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 rectangle          6  2629 Allis shad          Alosa alosa        A. alosa        11E0               15</span></span>
<span id="cb2-256"><a href="#cb2-256" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 rectangle         22  3003 European flounder   Platichthys flesus P. flesus       37E4                3</span></span>
<span id="cb2-257"><a href="#cb2-257" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 rectangle         26  4135 Sea trout           Salmo trutta       S. trutta       38F8                1</span></span>
<span id="cb2-258"><a href="#cb2-258" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 division           6    44 Allis shad          Alosa alosa        A. alosa        27.7.g             12</span></span>
<span id="cb2-259"><a href="#cb2-259" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 division          13    47 European eel        Anguilla anguilla  A. anguilla     27.7.d             15</span></span>
<span id="cb2-260"><a href="#cb2-260" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 rectangle         25  3656 Atlantic salmon     Salmo salar        S. salar        39F2                1</span></span>
<span id="cb2-261"><a href="#cb2-261" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 rectangle         13  3081 European eel        Anguilla anguilla  A. anguilla     29E5                2</span></span>
<span id="cb2-262"><a href="#cb2-262" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 rectangle         19  3076 Thinlip grey mullet Chelon ramada      C. ramada       24E5                5</span></span>
<span id="cb2-263"><a href="#cb2-263" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 rectangle         20  2158 European smelt      Osmerus eperlanus  O. eperlanus    30D5                1</span></span>
<span id="cb2-264"><a href="#cb2-264" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-265"><a href="#cb2-265" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_basin&quot;&gt; [?? x 3]</span></span>
<span id="cb2-266"><a href="#cb2-266" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-267"><a href="#cb2-267" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_name basin_id geom                                                                                     </span></span>
<span id="cb2-268"><a href="#cb2-268" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;         &lt;int&gt; &lt;pq_gmtry&gt;                                                                               </span></span>
<span id="cb2-269"><a href="#cb2-269" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 Aa                1 0103000020E61000000100000067000000B952D9131D8801401BBC172A2B5649408D0C014E4885014000E325…</span></span>
<span id="cb2-270"><a href="#cb2-270" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 Adour             3 0103000020E610000001000000640100003233CE8E170AE0BF1F91FFE9FC694540E2EB095DA9D0E0BFBCE4A2…</span></span>
<span id="cb2-271"><a href="#cb2-271" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 Alcoa           387 0103000020E61000000100000033000000ED59C15EDBBB21C0C7B0A13118C64340364D1B3C77BB21C0D8934B…</span></span>
<span id="cb2-272"><a href="#cb2-272" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 Anllons         358 0103000020E6100000010000004E000000B693D402240F21C0C2A361BB369A454051BC20BAD90B21C0EEAAAB…</span></span>
<span id="cb2-273"><a href="#cb2-273" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 Artibai         359 0103000020E6100000010000001A00000050DD05F9C08103C02E478DC051A045400788A472099703C08C6A78…</span></span>
<span id="cb2-274"><a href="#cb2-274" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 Ason            290 0103000020E61000000100000038000000315B7B490DE20BC0E120DA39AE92454050BEFE9623160CC0FCD576…</span></span>
<span id="cb2-275"><a href="#cb2-275" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 Aulne            14 0103000020E6100000010000005D000000D85741AAE4E60BC00A3519C6FB1A48409BF318828CDD0BC008C323…</span></span>
<span id="cb2-276"><a href="#cb2-276" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 Authie           15 0103000020E6100000010000007C000000234C696EBAA7044062A2A7E6470C49405AFD67A2D9810440EE7E4C…</span></span>
<span id="cb2-277"><a href="#cb2-277" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 Auzance          16 0103000020E61000000100000034000000F6C13D5D7E32F8BF28CAD72761454740E79CF4DA6972F8BFC84B2D…</span></span>
<span id="cb2-278"><a href="#cb2-278" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 Ave             385 0103000020E6100000010000006B0000009EE0BE53973420C09E8644EE81C544404F8DBB263F2F20C06C85FA…</span></span>
<span id="cb2-279"><a href="#cb2-279" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-280"><a href="#cb2-280" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_species_ices_occurence&quot;&gt; [?? x 8]</span></span>
<span id="cb2-281"><a href="#cb2-281" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-282"><a href="#cb2-282" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ices_type   gid species_id fish_name         icesname latin_name           simplified_name nb_occurence</span></span>
<span id="cb2-283"><a href="#cb2-283" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;int&gt;      &lt;int&gt; &lt;chr&gt;             &lt;chr&gt;    &lt;chr&gt;                &lt;chr&gt;                &lt;int64&gt;</span></span>
<span id="cb2-284"><a href="#cb2-284" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 rectangle  3159          4 European sturgeon 22E6     Acipenser sturio     A. sturio                  0</span></span>
<span id="cb2-285"><a href="#cb2-285" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 rectangle  3159          6 Allis shad        22E6     Alosa alosa          A. alosa                   5</span></span>
<span id="cb2-286"><a href="#cb2-286" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 rectangle  3159          8 Twaite shad       22E6     Alosa fallax         A. fallax                  1</span></span>
<span id="cb2-287"><a href="#cb2-287" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 rectangle  3159         13 European eel      22E6     Anguilla anguilla    A. anguilla                0</span></span>
<span id="cb2-288"><a href="#cb2-288" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 rectangle  3159         18 River lamprey     22E6     Lampetra fluviatilis L. fluviatilis             0</span></span>
<span id="cb2-289"><a href="#cb2-289" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 rectangle  3159         20 European smelt    22E6     Osmerus eperlanus    O. eperlanus               0</span></span>
<span id="cb2-290"><a href="#cb2-290" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 rectangle  3159         21 Sea lamprey       22E6     Petromyzon marinus   P. marinus                 0</span></span>
<span id="cb2-291"><a href="#cb2-291" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 rectangle  3159         22 European flounder 22E6     Platichthys flesus   P. flesus                  0</span></span>
<span id="cb2-292"><a href="#cb2-292" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 rectangle  3159         25 Atlantic salmon   22E6     Salmo salar          S. salar                   0</span></span>
<span id="cb2-293"><a href="#cb2-293" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 rectangle  3159         26 Sea trout         22E6     Salmo trutta         S. trutta                  0</span></span>
<span id="cb2-294"><a href="#cb2-294" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-295"><a href="#cb2-295" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_hybrid_model&quot;&gt; [?? x 17]</span></span>
<span id="cb2-296"><a href="#cb2-296" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-297"><a href="#cb2-297" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    hybrid_model_result_id basin_id species_id climatic_model_id  year   nit    hsi saturation_rate climatic_scenar…</span></span>
<span id="cb2-298"><a href="#cb2-298" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                     &lt;int&gt;    &lt;int&gt;      &lt;int&gt;             &lt;int&gt; &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;           </span></span>
<span id="cb2-299"><a href="#cb2-299" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                      3        1          6                 2  1951 1176. 0.244            0.558 rcp45           </span></span>
<span id="cb2-300"><a href="#cb2-300" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                      4        1          6                 2  1952 1144. 0.322            0.411 rcp45           </span></span>
<span id="cb2-301"><a href="#cb2-301" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                      5        1          6                 2  1953 1120. 0.195            0.666 rcp45           </span></span>
<span id="cb2-302"><a href="#cb2-302" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                      6        1          6                 2  1954 1097. 0.246            0.517 rcp45           </span></span>
<span id="cb2-303"><a href="#cb2-303" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                      7        1          6                 2  1955  734. 0.0850           1     rcp45           </span></span>
<span id="cb2-304"><a href="#cb2-304" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                      8        1          6                 2  1956  998. 0.235            0.491 rcp45           </span></span>
<span id="cb2-305"><a href="#cb2-305" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                      9        1          6                 2  1957  949. 0.327            0.336 rcp45           </span></span>
<span id="cb2-306"><a href="#cb2-306" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                     10        1          6                 2  1958  912. 0.415            0.254 rcp45           </span></span>
<span id="cb2-307"><a href="#cb2-307" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                     11        1          6                 2  1959  724. 0.246            0.342 rcp45           </span></span>
<span id="cb2-308"><a href="#cb2-308" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                     12        1          6                 2  1960  670. 0.380            0.204 rcp45           </span></span>
<span id="cb2-309"><a href="#cb2-309" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 8 more variables: climatic_model_code &lt;chr&gt;, oceanic_model &lt;chr&gt;,</span></span>
<span id="cb2-310"><a href="#cb2-310" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   atmospheric_model &lt;chr&gt;, climatic_model_hm &lt;chr&gt;, basin_name &lt;chr&gt;, fish_name &lt;chr&gt;, latin_name &lt;chr&gt;,</span></span>
<span id="cb2-311"><a href="#cb2-311" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   simplified_name &lt;chr&gt;</span></span>
<span id="cb2-312"><a href="#cb2-312" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;species_iucn&quot;&gt; [?? x 4]</span></span>
<span id="cb2-313"><a href="#cb2-313" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-314"><a href="#cb2-314" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_iucn_id species_id iucn_classification_id iucn_level_id</span></span>
<span id="cb2-315"><a href="#cb2-315" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;              &lt;int&gt;      &lt;int&gt;                  &lt;int&gt;         &lt;int&gt;</span></span>
<span id="cb2-316"><a href="#cb2-316" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1               1          4                      1             4</span></span>
<span id="cb2-317"><a href="#cb2-317" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2               2         13                      1             4</span></span>
<span id="cb2-318"><a href="#cb2-318" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3               3         18                      1             8</span></span>
<span id="cb2-319"><a href="#cb2-319" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4               4         21                      1             8</span></span>
<span id="cb2-320"><a href="#cb2-320" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5               5         25                      1             8</span></span>
<span id="cb2-321"><a href="#cb2-321" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6               6         26                      1             8</span></span>
<span id="cb2-322"><a href="#cb2-322" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7               7         20                      1             8</span></span>
<span id="cb2-323"><a href="#cb2-323" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8               8         19                      1             8</span></span>
<span id="cb2-324"><a href="#cb2-324" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9               9          6                      1             8</span></span>
<span id="cb2-325"><a href="#cb2-325" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10              10         22                      1             8</span></span>
<span id="cb2-326"><a href="#cb2-326" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-327"><a href="#cb2-327" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ices_area&quot;&gt; [?? x 11]</span></span>
<span id="cb2-328"><a href="#cb2-328" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-329"><a href="#cb2-329" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      gid major_fa subarea division subdivisio unit  area_full area_27 area_km2 geom         simplified_geom     </span></span>
<span id="cb2-330"><a href="#cb2-330" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;pq_gmtry&gt;   &lt;pq_gmtry&gt;          </span></span>
<span id="cb2-331"><a href="#cb2-331" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1    83 27       8       e        &lt;NA&gt;       &lt;NA&gt;  27.8.e    8.e          NA  01030000201… 0103000020E61000000…</span></span>
<span id="cb2-332"><a href="#cb2-332" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2    10 27       4       a        &lt;NA&gt;       &lt;NA&gt;  27.4.a    4.a      267336. 01060000201… 0106000020E61000000…</span></span>
<span id="cb2-333"><a href="#cb2-333" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3     7 27       4       c        &lt;NA&gt;       &lt;NA&gt;  27.4.c    4.c       63634. 01060000201… 0103000020E61000006…</span></span>
<span id="cb2-334"><a href="#cb2-334" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4    72 27       3       a        &lt;NA&gt;       &lt;NA&gt;  27.3.a    3.a          NA  01030000201… 0103000020E61000005…</span></span>
<span id="cb2-335"><a href="#cb2-335" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5    27 27       6       a        &lt;NA&gt;       &lt;NA&gt;  27.6.a    6.a      236759. 01060000201… 0103000020E61000009…</span></span>
<span id="cb2-336"><a href="#cb2-336" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6     8 27       4       b        &lt;NA&gt;       &lt;NA&gt;  27.4.b    4.b      280957. 01060000201… 0103000020E61000006…</span></span>
<span id="cb2-337"><a href="#cb2-337" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7    84 27       9       b        &lt;NA&gt;       &lt;NA&gt;  27.9.b    9.b          NA  01030000201… 0103000020E61000000…</span></span>
<span id="cb2-338"><a href="#cb2-338" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8    82 27       8       d        &lt;NA&gt;       &lt;NA&gt;  27.8.d    8.d          NA  01030000201… 0103000020E61000000…</span></span>
<span id="cb2-339"><a href="#cb2-339" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9    36 27       9       a        &lt;NA&gt;       &lt;NA&gt;  27.9.a    9.a      167855. 01060000201… 0106000020E61000000…</span></span>
<span id="cb2-340"><a href="#cb2-340" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10    78 27       6       b        &lt;NA&gt;       &lt;NA&gt;  27.6.b    6.b          NA  01030000201… 0103000020E61000000…</span></span>
<span id="cb2-341"><a href="#cb2-341" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-342"><a href="#cb2-342" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ices_rectangle&quot;&gt; [?? x 15]</span></span>
<span id="cb2-343"><a href="#cb2-343" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-344"><a href="#cb2-344" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      gid    id icesname south  west north  east area_km2 objectid ecoregion           area percentage shape_star</span></span>
<span id="cb2-345"><a href="#cb2-345" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt;  &lt;int64&gt; &lt;chr&gt;              &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;</span></span>
<span id="cb2-346"><a href="#cb2-346" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1  1846  2549 01D2      36     -18  36.5   -17     4987       30 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-347"><a href="#cb2-347" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2  1847  2550 02D2      36.5   -18  37     -17     4955      121 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-348"><a href="#cb2-348" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3  1848  2551 03D2      37     -18  37.5   -17     4923      209 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-349"><a href="#cb2-349" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4  1849  2552 04D2      37.5   -18  38     -17     4891      296 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-350"><a href="#cb2-350" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5  1850  2553 05D2      38     -18  38.5   -17     4858      385 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-351"><a href="#cb2-351" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6  1851  2554 06D2      38.5   -18  39     -17     4825      463 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-352"><a href="#cb2-352" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7  1852  2555 07D2      39     -18  39.5   -17     4792      538 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-353"><a href="#cb2-353" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8  1853  2556 08D2      39.5   -18  40     -17     4758      624 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-354"><a href="#cb2-354" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9  1854  2557 09D2      40     -18  40.5   -17     4724      715 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-355"><a href="#cb2-355" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10  1855  2558 10D2      40.5   -18  41     -17     4689      806 Oceanic Northeast…   0.5        100      0.500</span></span>
<span id="cb2-356"><a href="#cb2-356" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 2 more variables: shape_stle &lt;dbl&gt;, geom &lt;pq_gmtry&gt;</span></span>
<span id="cb2-357"><a href="#cb2-357" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;iucn_classification&quot;&gt; [?? x 3]</span></span>
<span id="cb2-358"><a href="#cb2-358" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-359"><a href="#cb2-359" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   iucn_classification_id iucn_classification_code bibliography                                                  </span></span>
<span id="cb2-360"><a href="#cb2-360" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    &lt;int&gt; &lt;chr&gt;                    &lt;chr&gt;                                                         </span></span>
<span id="cb2-361"><a href="#cb2-361" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1                      3 IUCN_FR                  UICN Comité français, MNHN, SFI &amp; AFB. (2019) La Liste rouge …</span></span>
<span id="cb2-362"><a href="#cb2-362" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2                      4 IUCN_IE                  King, J.L., F. Marnell, N. Kingston, R. Rosell, P. Boylan, J.…</span></span>
<span id="cb2-363"><a href="#cb2-363" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3                      2 IUCN_ES                  www.uicn.es/web/pdf/Tablas_especies_informe_RedList_Spain.xlsx</span></span>
<span id="cb2-364"><a href="#cb2-364" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4                      1 IUCN_Europe              Brooks, Emma. European Red List of Freshwater Fishes. Luxembo…</span></span>
<span id="cb2-365"><a href="#cb2-365" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5                      6 IUCN_UK                  https://hub.jncc.gov.uk/assets/478f7160-967b-4366-acdf-8941fd…</span></span>
<span id="cb2-366"><a href="#cb2-366" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6                      5 IUCN_PT                  Cabral, M.J. (coord), Almeida, J., Almeida, P.R., Dellinger T…</span></span>
<span id="cb2-367"><a href="#cb2-367" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;iucn_level&quot;&gt; [?? x 3]</span></span>
<span id="cb2-368"><a href="#cb2-368" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-369"><a href="#cb2-369" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    iucn_level_id iucn_level_code iucn_level_name      </span></span>
<span id="cb2-370"><a href="#cb2-370" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;            &lt;int&gt; &lt;chr&gt;           &lt;chr&gt;                </span></span>
<span id="cb2-371"><a href="#cb2-371" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1             1 EX              Extinct              </span></span>
<span id="cb2-372"><a href="#cb2-372" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2             2 EW              Extinct in the Wild  </span></span>
<span id="cb2-373"><a href="#cb2-373" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3             3 RE              Regionally Extinct   </span></span>
<span id="cb2-374"><a href="#cb2-374" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4             4 CR              Critically Endangered</span></span>
<span id="cb2-375"><a href="#cb2-375" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5             5 EN              Endangered           </span></span>
<span id="cb2-376"><a href="#cb2-376" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6             6 VU              Vulnerable           </span></span>
<span id="cb2-377"><a href="#cb2-377" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7             7 NT              Near Threatened      </span></span>
<span id="cb2-378"><a href="#cb2-378" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8             8 LC              Least Concern        </span></span>
<span id="cb2-379"><a href="#cb2-379" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9             9 DD              Data Deficient       </span></span>
<span id="cb2-380"><a href="#cb2-380" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10            10 NE              Not Evaluated        </span></span>
<span id="cb2-381"><a href="#cb2-381" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;species_division&quot;&gt; [?? x 4]</span></span>
<span id="cb2-382"><a href="#cb2-382" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-383"><a href="#cb2-383" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_division_id  year species_id   gid</span></span>
<span id="cb2-384"><a href="#cb2-384" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                  &lt;int&gt; &lt;int&gt;      &lt;int&gt; &lt;int&gt;</span></span>
<span id="cb2-385"><a href="#cb2-385" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                   1  2013          4    37</span></span>
<span id="cb2-386"><a href="#cb2-386" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                   2  2015          4    47</span></span>
<span id="cb2-387"><a href="#cb2-387" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                   3  2015          4    40</span></span>
<span id="cb2-388"><a href="#cb2-388" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                   4  2016          4    40</span></span>
<span id="cb2-389"><a href="#cb2-389" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                   5  2016          4    39</span></span>
<span id="cb2-390"><a href="#cb2-390" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                   6  2016          4    47</span></span>
<span id="cb2-391"><a href="#cb2-391" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                   7  2017          4    39</span></span>
<span id="cb2-392"><a href="#cb2-392" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                   8  2003          6     7</span></span>
<span id="cb2-393"><a href="#cb2-393" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                   9  2003          6    40</span></span>
<span id="cb2-394"><a href="#cb2-394" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                  10  2003          6    39</span></span>
<span id="cb2-395"><a href="#cb2-395" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-396"><a href="#cb2-396" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;species_rectangle&quot;&gt; [?? x 4]</span></span>
<span id="cb2-397"><a href="#cb2-397" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-398"><a href="#cb2-398" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_rectangle_id  year species_id   gid</span></span>
<span id="cb2-399"><a href="#cb2-399" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                   &lt;int&gt; &lt;int&gt;      &lt;int&gt; &lt;int&gt;</span></span>
<span id="cb2-400"><a href="#cb2-400" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                    1  2013          4  3234</span></span>
<span id="cb2-401"><a href="#cb2-401" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                    2  2015          4  3324</span></span>
<span id="cb2-402"><a href="#cb2-402" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                    3  2015          4  3565</span></span>
<span id="cb2-403"><a href="#cb2-403" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                    4  2016          4  3323</span></span>
<span id="cb2-404"><a href="#cb2-404" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                    5  2016          4  3324</span></span>
<span id="cb2-405"><a href="#cb2-405" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                    6  2016          4  3485</span></span>
<span id="cb2-406"><a href="#cb2-406" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                    7  2017          4  3323</span></span>
<span id="cb2-407"><a href="#cb2-407" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                    8  2003          6  3323</span></span>
<span id="cb2-408"><a href="#cb2-408" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                    9  2003          6  3324</span></span>
<span id="cb2-409"><a href="#cb2-409" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                   10  2003          6  3160</span></span>
<span id="cb2-410"><a href="#cb2-410" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-411"><a href="#cb2-411" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_ices_geom&quot;&gt; [?? x 4]</span></span>
<span id="cb2-412"><a href="#cb2-412" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-413"><a href="#cb2-413" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ices_type   gid icesname geom                                                                                </span></span>
<span id="cb2-414"><a href="#cb2-414" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;    &lt;pq_gmtry&gt;                                                                          </span></span>
<span id="cb2-415"><a href="#cb2-415" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 rectangle  3159 22E6     0106000020E6100000010000000103000000010000000500000080FFFFFFFFFF0FC02892FFFFFF3F474…</span></span>
<span id="cb2-416"><a href="#cb2-416" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 rectangle  2247 21D6     0106000020E610000001000000010300000001000000050000006048FEFFFFFF2BC018C9FFFFFFFF464…</span></span>
<span id="cb2-417"><a href="#cb2-417" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 rectangle  2256 30D6     0106000020E610000001000000010300000001000000050000006048FEFFFFFF2BC018C9FFFFFF3F494…</span></span>
<span id="cb2-418"><a href="#cb2-418" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 rectangle  1966 27D3     0106000020E61000000100000001030000000100000005000000D06D0000000031C0E86D00000080484…</span></span>
<span id="cb2-419"><a href="#cb2-419" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 rectangle  3177 44E6     0106000020E6100000010000000103000000010000000500000080FFFFFFFFFF0FC0D8A4000000C04C4…</span></span>
<span id="cb2-420"><a href="#cb2-420" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 rectangle  4058 37F7     0106000020E610000001000000010300000001000000050000004022F9FFFFFF1B40F836000000004B4…</span></span>
<span id="cb2-421"><a href="#cb2-421" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 rectangle  2258 32D6     0106000020E610000001000000010300000001000000050000006048FEFFFFFF2BC0385BFFFFFFBF494…</span></span>
<span id="cb2-422"><a href="#cb2-422" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 rectangle  2727 12E1     0106000020E610000001000000010300000001000000050000002024FFFFFFFF21C018C9FFFFFFBF444…</span></span>
<span id="cb2-423"><a href="#cb2-423" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 rectangle  3092 40E5     0106000020E61000000100000001030000000100000005000000C090FCFFFFFF13C02892FFFFFFBF4B4…</span></span>
<span id="cb2-424"><a href="#cb2-424" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 rectangle  2052 19D4     0106000020E6100000010000000103000000010000000500000090490100000030C0F83600000080464…</span></span>
<span id="cb2-425"><a href="#cb2-425" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-426"><a href="#cb2-426" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;esvalue&quot;&gt; [?? x 3]</span></span>
<span id="cb2-427"><a href="#cb2-427" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-428"><a href="#cb2-428" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   esvalue_id esvalue_code esvalue_name</span></span>
<span id="cb2-429"><a href="#cb2-429" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;       </span></span>
<span id="cb2-430"><a href="#cb2-430" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1         -1 ?            Unknown     </span></span>
<span id="cb2-431"><a href="#cb2-431" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2          0 0            Not present </span></span>
<span id="cb2-432"><a href="#cb2-432" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3          1 €            Low value   </span></span>
<span id="cb2-433"><a href="#cb2-433" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4          2 €€           Median value</span></span>
<span id="cb2-434"><a href="#cb2-434" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5          3 €€€          High value  </span></span>
<span id="cb2-435"><a href="#cb2-435" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;locale&quot;&gt; [?? x 4]</span></span>
<span id="cb2-436"><a href="#cb2-436" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-437"><a href="#cb2-437" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    locale_id country_code english_label              country_label                        </span></span>
<span id="cb2-438"><a href="#cb2-438" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;                      &lt;chr&gt;                                </span></span>
<span id="cb2-439"><a href="#cb2-439" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1        59 fr           ALL EXISTING SUBCATEGORIES TOUTES LES SOUS-CATEGORIES EXISTANTES</span></span>
<span id="cb2-440"><a href="#cb2-440" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2        60 fr           Allis shad                 Grande alose                         </span></span>
<span id="cb2-441"><a href="#cb2-441" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3        61 fr           Atlantic salmon            Saumon atlantique                    </span></span>
<span id="cb2-442"><a href="#cb2-442" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4        62 fr           Barrow                     Barrow                               </span></span>
<span id="cb2-443"><a href="#cb2-443" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5        63 fr           Couesnon                   Couesnon                             </span></span>
<span id="cb2-444"><a href="#cb2-444" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6        64 fr           Cultural services          Services culturels                   </span></span>
<span id="cb2-445"><a href="#cb2-445" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7        65 fr           Deba                       Deba                                 </span></span>
<span id="cb2-446"><a href="#cb2-446" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8        66 fr           Dordogne                   Dordogne                             </span></span>
<span id="cb2-447"><a href="#cb2-447" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9        67 fr           Dorset Frome               Dorset Frome                         </span></span>
<span id="cb2-448"><a href="#cb2-448" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10        68 fr           European eel               Anguille européenne                  </span></span>
<span id="cb2-449"><a href="#cb2-449" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-450"><a href="#cb2-450" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;hybrid_model_result&quot;&gt; [?? x 9]</span></span>
<span id="cb2-451"><a href="#cb2-451" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-452"><a href="#cb2-452" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    hybrid_model_result_id basin_id species_id climatic_model_id climatic_scenario  year   nit    hsi saturation_rate</span></span>
<span id="cb2-453"><a href="#cb2-453" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                     &lt;int&gt;    &lt;int&gt;      &lt;int&gt;             &lt;int&gt; &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt;           &lt;dbl&gt;</span></span>
<span id="cb2-454"><a href="#cb2-454" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                      2        1          6                 2 rcp45                 0 1451. 0.168            1    </span></span>
<span id="cb2-455"><a href="#cb2-455" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                      3        1          6                 2 rcp45              1951 1176. 0.244            0.558</span></span>
<span id="cb2-456"><a href="#cb2-456" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                      4        1          6                 2 rcp45              1952 1144. 0.322            0.411</span></span>
<span id="cb2-457"><a href="#cb2-457" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                      5        1          6                 2 rcp45              1953 1120. 0.195            0.666</span></span>
<span id="cb2-458"><a href="#cb2-458" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                      6        1          6                 2 rcp45              1954 1097. 0.246            0.517</span></span>
<span id="cb2-459"><a href="#cb2-459" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                      7        1          6                 2 rcp45              1955  734. 0.0850           1    </span></span>
<span id="cb2-460"><a href="#cb2-460" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                      8        1          6                 2 rcp45              1956  998. 0.235            0.491</span></span>
<span id="cb2-461"><a href="#cb2-461" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                      9        1          6                 2 rcp45              1957  949. 0.327            0.336</span></span>
<span id="cb2-462"><a href="#cb2-462" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                     10        1          6                 2 rcp45              1958  912. 0.415            0.254</span></span>
<span id="cb2-463"><a href="#cb2-463" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                     11        1          6                 2 rcp45              1959  724. 0.246            0.342</span></span>
<span id="cb2-464"><a href="#cb2-464" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-465"><a href="#cb2-465" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;casestudy&quot;&gt; [?? x 4]</span></span>
<span id="cb2-466"><a href="#cb2-466" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-467"><a href="#cb2-467" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   casestudy_id casestudy_name           publishable geom                                                        </span></span>
<span id="cb2-468"><a href="#cb2-468" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          &lt;int&gt; &lt;chr&gt;                    &lt;lgl&gt;       &lt;pq_gmtry&gt;                                                  </span></span>
<span id="cb2-469"><a href="#cb2-469" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1            3 Normand-Breton Gulf      TRUE        0103000020E6100000010000003A010000D08FF885F7A4F0BFCA66C74A9…</span></span>
<span id="cb2-470"><a href="#cb2-470" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2            4 Loire                    TRUE        0106000020E61000000400000001030000000100000005000000E71D48D…</span></span>
<span id="cb2-471"><a href="#cb2-471" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            6 Gipuzcoan                TRUE        0106000020E610000002000000010300000001000000FA000000F5690FD…</span></span>
<span id="cb2-472"><a href="#cb2-472" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4            1 Waterford Harbour        TRUE        0106000020E610000002000000010300000003000000840200004472DEF…</span></span>
<span id="cb2-473"><a href="#cb2-473" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5            9 Mondego                  TRUE        0106000020E6100000020000000103000000010000006502000090455BF…</span></span>
<span id="cb2-474"><a href="#cb2-474" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6            8 Minho                    TRUE        0103000020E610000001000000B7040000295C2F83AAE61BC0CC7D996F0…</span></span>
<span id="cb2-475"><a href="#cb2-475" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7            2 Tamar-Taff-Frome         TRUE        0106000020E610000003000000010300000001000000CA00000019C5EAD…</span></span>
<span id="cb2-476"><a href="#cb2-476" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8            5 Gironde-Garonne-Dordogne TRUE        0106000020E61000000200000001030000000400000065080000ABC3407…</span></span>
<span id="cb2-477"><a href="#cb2-477" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9            7 Ulla                     TRUE        0103000020E61000000100000066010000AF11015F00D71FC093CDADAA1…</span></span>
<span id="cb2-478"><a href="#cb2-478" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ecosystemic_services&quot;&gt; [?? x 5]</span></span>
<span id="cb2-479"><a href="#cb2-479" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-480"><a href="#cb2-480" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    ecosystemic_services_id casestudy_id species_id subcategory_id esvalue_id</span></span>
<span id="cb2-481"><a href="#cb2-481" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                      &lt;int&gt;        &lt;int&gt;      &lt;int&gt;          &lt;int&gt;      &lt;int&gt;</span></span>
<span id="cb2-482"><a href="#cb2-482" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                      89            1          6              1          0</span></span>
<span id="cb2-483"><a href="#cb2-483" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                      99            1          8              1          0</span></span>
<span id="cb2-484"><a href="#cb2-484" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                      95            1         18              1          0</span></span>
<span id="cb2-485"><a href="#cb2-485" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                      96            1         21              1          0</span></span>
<span id="cb2-486"><a href="#cb2-486" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                      90            1         25              1          0</span></span>
<span id="cb2-487"><a href="#cb2-487" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                      97            1         26              1         -1</span></span>
<span id="cb2-488"><a href="#cb2-488" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                      93            1         20              1         -1</span></span>
<span id="cb2-489"><a href="#cb2-489" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                      94            1          4              1          0</span></span>
<span id="cb2-490"><a href="#cb2-490" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                      91            1         13              1         -1</span></span>
<span id="cb2-491"><a href="#cb2-491" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                      92            1         22              1          1</span></span>
<span id="cb2-492"><a href="#cb2-492" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-493"><a href="#cb2-493" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;basin&quot;&gt; [?? x 12]</span></span>
<span id="cb2-494"><a href="#cb2-494" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-495"><a href="#cb2-495" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_id basin_name   country ecoregion_code longitude latitude surface_area_drainage_basin length_main_wate…</span></span>
<span id="cb2-496"><a href="#cb2-496" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;                       &lt;dbl&gt;             &lt;dbl&gt;</span></span>
<span id="cb2-497"><a href="#cb2-497" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1       15 Authie       France           20025      1.63     50.4                        1305               100</span></span>
<span id="cb2-498"><a href="#cb2-498" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2      228 Vosso        Norway           20022      5.72     60.5                          NA                NA</span></span>
<span id="cb2-499"><a href="#cb2-499" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3      229 Laerdalselva Norway           20022      7.46     61.1                          NA                NA</span></span>
<span id="cb2-500"><a href="#cb2-500" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4      230 Aroelva      Norway           20022      7.16     61.3                          NA                NA</span></span>
<span id="cb2-501"><a href="#cb2-501" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5      235 Figgjo       Norway           20022      5.83     58.8                          NA                NA</span></span>
<span id="cb2-502"><a href="#cb2-502" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6      236 Etneelv      Norway           20022      5.92     59.7                          NA                NA</span></span>
<span id="cb2-503"><a href="#cb2-503" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7      237 Opo          Norway           20022      6.54     60.1                          NA                NA</span></span>
<span id="cb2-504"><a href="#cb2-504" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8      238 Loneelv      Norway           20022      5.05     60.8                          NA                NA</span></span>
<span id="cb2-505"><a href="#cb2-505" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9      231 Eira         Norway           20022      8.14     62.7                          NA                NA</span></span>
<span id="cb2-506"><a href="#cb2-506" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10      239 Bondalselv   Norway           20022      6.38     62.3                          NA                NA</span></span>
<span id="cb2-507"><a href="#cb2-507" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 4 more variables: altitude_source &lt;dbl&gt;, bibliography &lt;chr&gt;, administrator &lt;chr&gt;,</span></span>
<span id="cb2-508"><a href="#cb2-508" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   link_pictures &lt;chr&gt;</span></span>
<span id="cb2-509"><a href="#cb2-509" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;basin_outlet&quot;&gt; [?? x 9]</span></span>
<span id="cb2-510"><a href="#cb2-510" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-511"><a href="#cb2-511" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    basin_id  wso_id ccm_name ccm_area ccm_window geom      seaoutlet_geom   simplified_geom   verysimplified_ge…</span></span>
<span id="cb2-512"><a href="#cb2-512" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       &lt;int&gt;   &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;      &lt;int&gt; &lt;pq_gmtr&gt; &lt;pq_gmtry&gt;       &lt;pq_gmtry&gt;        &lt;pq_gmtry&gt;        </span></span>
<span id="cb2-513"><a href="#cb2-513" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1      147   83758 Spey        3061.       2001 01060000… 0101000020E6100… 0103000020E61000… 0103000020E610000…</span></span>
<span id="cb2-514"><a href="#cb2-514" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2      155   83745 Tay         5902.       2001 01060000… 0101000020E6100… 0103000020E61000… 0103000020E610000…</span></span>
<span id="cb2-515"><a href="#cb2-515" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3      137  291745 &lt;NA&gt;        1014.       2003 01060000… 0101000020E6100… 0103000020E61000… 0103000020E610000…</span></span>
<span id="cb2-516"><a href="#cb2-516" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4       65 1034751 &lt;NA&gt;       51464.       2008 01060000… 0101000020E6100… 0106000020E61000… 0106000020E610000…</span></span>
<span id="cb2-517"><a href="#cb2-517" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5      232 1034818 &lt;NA&gt;        3182.       2008 01060000… 0101000020E6100… 0106000020E61000… 0106000020E610000…</span></span>
<span id="cb2-518"><a href="#cb2-518" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6      242 1034790 Vefsna      4218.       2008 01060000… 0101000020E6100… 0103000020E61000… 0103000020E610000…</span></span>
<span id="cb2-519"><a href="#cb2-519" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7      177  291146 Vilaine    10490.       2003 01060000… 0101000020E6100… 0103000020E61000… 0103000020E610000…</span></span>
<span id="cb2-520"><a href="#cb2-520" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8      233 1034734 &lt;NA&gt;        6163.       2008 01060000… 0101000020E6100… 0106000020E61000… 0106000020E610000…</span></span>
<span id="cb2-521"><a href="#cb2-521" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9      271   83811 Thames     13514.       2001 01060000… 0101000020E6100… 0106000020E61000… 0106000020E610000…</span></span>
<span id="cb2-522"><a href="#cb2-522" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10       62 1034724 Glomma     41911        2008 01060000… 0101000020E6100… 0106000020E61000… 0106000020E610000…</span></span>
<span id="cb2-523"><a href="#cb2-523" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-524"><a href="#cb2-524" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;casestudy_basin&quot;&gt; [?? x 2]</span></span>
<span id="cb2-525"><a href="#cb2-525" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-526"><a href="#cb2-526" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    casestudy_id basin_id</span></span>
<span id="cb2-527"><a href="#cb2-527" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           &lt;int&gt;    &lt;int&gt;</span></span>
<span id="cb2-528"><a href="#cb2-528" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1            1       20</span></span>
<span id="cb2-529"><a href="#cb2-529" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2            2      330</span></span>
<span id="cb2-530"><a href="#cb2-530" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3            2      331</span></span>
<span id="cb2-531"><a href="#cb2-531" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4            2      329</span></span>
<span id="cb2-532"><a href="#cb2-532" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5            3       36</span></span>
<span id="cb2-533"><a href="#cb2-533" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6            3      137</span></span>
<span id="cb2-534"><a href="#cb2-534" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7            4       89</span></span>
<span id="cb2-535"><a href="#cb2-535" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8            5      382</span></span>
<span id="cb2-536"><a href="#cb2-536" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9            5       60</span></span>
<span id="cb2-537"><a href="#cb2-537" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10            6      362</span></span>
<span id="cb2-538"><a href="#cb2-538" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-539"><a href="#cb2-539" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;climatic_model&quot;&gt; [?? x 5]</span></span>
<span id="cb2-540"><a href="#cb2-540" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-541"><a href="#cb2-541" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    climatic_model_id climatic_model_code oceanic_model atmospheric_model           climatic_model_hm</span></span>
<span id="cb2-542"><a href="#cb2-542" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                &lt;int&gt; &lt;chr&gt;               &lt;chr&gt;         &lt;chr&gt;                       &lt;chr&gt;            </span></span>
<span id="cb2-543"><a href="#cb2-543" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1                 1 canesm2             CanESM2       &quot;CCCma-CanESM2&quot;             &quot;&quot;               </span></span>
<span id="cb2-544"><a href="#cb2-544" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2                 2 cnrmcm5             CNRM-CM5      &quot;CNRM-CERFACS-CNRM-CM5&quot;     &quot;cn&quot;             </span></span>
<span id="cb2-545"><a href="#cb2-545" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3                 3 csiromk360          CSIRO-Mk3-6-0 &quot;CSIRO-QCCCE-CSIRO-Mk3-6-0&quot; &quot;cs&quot;             </span></span>
<span id="cb2-546"><a href="#cb2-546" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4                 4 gfdlesm2m           GFDL-ESM2M    &quot;NOAA-GFDL-GFDL-ESM2M&quot;      &quot;&quot;               </span></span>
<span id="cb2-547"><a href="#cb2-547" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5                 5 hadgem2es           HadGEM2-ES    &quot;MOHC-HadGEM2-ES&quot;           &quot;&quot;               </span></span>
<span id="cb2-548"><a href="#cb2-548" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6                 6 ipslcm5amr          IPSL-CM5A-MR  &quot;IPSL-IPSL-CM5A-MR&quot;         &quot;&quot;               </span></span>
<span id="cb2-549"><a href="#cb2-549" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7                 7 miroc5              MIROC5        &quot;MIROC-MIROC5&quot;              &quot;&quot;               </span></span>
<span id="cb2-550"><a href="#cb2-550" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8                 8 mpiesmmr            MPI-ESM_MR    &quot;MPI-M-MPI-ESM-LR&quot;          &quot;&quot;               </span></span>
<span id="cb2-551"><a href="#cb2-551" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9                 9 noresm1me           NorESM1-ME    &quot;NCC-NorESM1-M&quot;             &quot;no&quot;             </span></span>
<span id="cb2-552"><a href="#cb2-552" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10                10 access10            ACCESS1-0     &quot;&quot;                          &quot;&quot;               </span></span>
<span id="cb2-553"><a href="#cb2-553" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-554"><a href="#cb2-554" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;species&quot;&gt; [?? x 5]</span></span>
<span id="cb2-555"><a href="#cb2-555" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-556"><a href="#cb2-556" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    species_id latin_name                english_name local_name active</span></span>
<span id="cb2-557"><a href="#cb2-557" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         &lt;int&gt; &lt;chr&gt;                     &lt;chr&gt;        &lt;chr&gt;      &lt;lgl&gt; </span></span>
<span id="cb2-558"><a href="#cb2-558" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1          1 Acipenser gueldenstaedtii &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-559"><a href="#cb2-559" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2          2 Acipenser naccarii        &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-560"><a href="#cb2-560" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3          3 Acipenser stellatus       &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-561"><a href="#cb2-561" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4          5 Alosa algeriensis         &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-562"><a href="#cb2-562" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5          7 Alosa caspia              &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-563"><a href="#cb2-563" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6          9 Alosa immaculata          &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-564"><a href="#cb2-564" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7         10 Alosa kessleri            &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-565"><a href="#cb2-565" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8         11 Alosa tanaica             &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-566"><a href="#cb2-566" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9         12 Alosa volgensis           &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-567"><a href="#cb2-567" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10         14 Caspiomyzon wagneri       &lt;NA&gt;         &quot;&quot;         FALSE </span></span>
<span id="cb2-568"><a href="#cb2-568" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-569"><a href="#cb2-569" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;category&quot;&gt; [?? x 3]</span></span>
<span id="cb2-570"><a href="#cb2-570" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-571"><a href="#cb2-571" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   category_id category_name          sortorder</span></span>
<span id="cb2-572"><a href="#cb2-572" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;         &lt;int&gt; &lt;chr&gt;                      &lt;int&gt;</span></span>
<span id="cb2-573"><a href="#cb2-573" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1           2 Provisionning services         1</span></span>
<span id="cb2-574"><a href="#cb2-574" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2           3 Regulating services            2</span></span>
<span id="cb2-575"><a href="#cb2-575" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3           1 Cultural services              3</span></span>
<span id="cb2-576"><a href="#cb2-576" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;subcategory&quot;&gt; [?? x 3]</span></span>
<span id="cb2-577"><a href="#cb2-577" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-578"><a href="#cb2-578" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   subcategory_id subcategory_name                                                                    category_id</span></span>
<span id="cb2-579"><a href="#cb2-579" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;            &lt;int&gt; &lt;chr&gt;                                                                                     &lt;int&gt;</span></span>
<span id="cb2-580"><a href="#cb2-580" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1              1 Food provision from commercial fisheries                                                      2</span></span>
<span id="cb2-581"><a href="#cb2-581" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2              2 Option value associated to the unknown production of molecules                                2</span></span>
<span id="cb2-582"><a href="#cb2-582" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3              3 Redistribution of nutrients - nutrients transportation                                        3</span></span>
<span id="cb2-583"><a href="#cb2-583" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4              4 Traditional know-how (fishing techniques used) related to the commercial fisheries            1</span></span>
<span id="cb2-584"><a href="#cb2-584" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5              5 Traditional know-how related to the recreational fisheries                                    1</span></span>
<span id="cb2-585"><a href="#cb2-585" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6              6 Gastronomy around species including emotional brotherhood (festival, event, and fo…           1</span></span>
<span id="cb2-586"><a href="#cb2-586" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7              7 Natural heritage and natural diversity - the existence value                                  1</span></span>
<span id="cb2-587"><a href="#cb2-587" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8              8 Recreation sport fishing (incl. competition)                                                  1</span></span>
<span id="cb2-588"><a href="#cb2-588" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9              9 The potential for environmental education and research                                        1</span></span>
<span id="cb2-589"><a href="#cb2-589" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;v_maxvalue_es&quot;&gt; [?? x 4]</span></span>
<span id="cb2-590"><a href="#cb2-590" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-591"><a href="#cb2-591" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    category_id casestudy_id species_id esvalue_id</span></span>
<span id="cb2-592"><a href="#cb2-592" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          &lt;int&gt;        &lt;int&gt;      &lt;int&gt;      &lt;int&gt;</span></span>
<span id="cb2-593"><a href="#cb2-593" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1           2            8         13          1</span></span>
<span id="cb2-594"><a href="#cb2-594" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2           3            3          8          0</span></span>
<span id="cb2-595"><a href="#cb2-595" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3           2            8         20          0</span></span>
<span id="cb2-596"><a href="#cb2-596" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4           1            8         19          0</span></span>
<span id="cb2-597"><a href="#cb2-597" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5           3            8         19          0</span></span>
<span id="cb2-598"><a href="#cb2-598" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6           3            9         21          0</span></span>
<span id="cb2-599"><a href="#cb2-599" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7           3            6          6          1</span></span>
<span id="cb2-600"><a href="#cb2-600" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8           3            4          8          0</span></span>
<span id="cb2-601"><a href="#cb2-601" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9           1            5          6          2</span></span>
<span id="cb2-602"><a href="#cb2-602" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10           3            8          8          0</span></span>
<span id="cb2-603"><a href="#cb2-603" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-604"><a href="#cb2-604" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;lang85_85&quot;&gt; [?? x 12]</span></span>
<span id="cb2-605"><a href="#cb2-605" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-606"><a href="#cb2-606" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       id geom          fid   cat  cat_ basin_id wso_id ccm_name ccm_area ccm_window seaoutlet_   simplified     </span></span>
<span id="cb2-607"><a href="#cb2-607" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;int&gt; &lt;pq_gmtry&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;  &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;          </span></span>
<span id="cb2-608"><a href="#cb2-608" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1     1 0103000020…     1     2     6       65 1.03e6 &lt;NA&gt;       51464.       2008 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-609"><a href="#cb2-609" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2     2 0103000020…     2     4    17      271 8.38e4 Thames     13514.       2001 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-610"><a href="#cb2-610" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3     3 0103000020…     3     7    22       62 1.03e6 Glomma     41911        2008 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-611"><a href="#cb2-611" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4     4 0103000020…     4    15    38       51 6   e0 Elbe      143656.       2000 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-612"><a href="#cb2-612" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5     5 0103000020…     5    16    38       51 6   e0 Elbe      143656.       2000 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-613"><a href="#cb2-613" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6     6 0103000020…     6    17    38       51 6   e0 Elbe      143656.       2000 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-614"><a href="#cb2-614" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7     7 0103000020…     7    24    47       81 1.03e6 &lt;NA&gt;        8356.       2008 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-615"><a href="#cb2-615" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8     8 0103000020…     8    28    71       40 8.38e4 &lt;NA&gt;        1928.       2001 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-616"><a href="#cb2-616" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9     9 0103000020…     9    32    78      164 8.41e4 &lt;NA&gt;        1327.       2001 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-617"><a href="#cb2-617" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10    10 0103000020…    10    34    83       19 8.37e4 &lt;NA&gt;        5811.       2001 SRID=4326;P… SRID=4326;MULT…</span></span>
<span id="cb2-618"><a href="#cb2-618" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows</span></span>
<span id="cb2-619"><a href="#cb2-619" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;ices_grass&quot;&gt; [?? x 14]</span></span>
<span id="cb2-620"><a href="#cb2-620" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-621"><a href="#cb2-621" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       id geom              fid   cat   gid major_fa subarea division subdivisio unit  area_full area_27 area_km2</span></span>
<span id="cb2-622"><a href="#cb2-622" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;int&gt; &lt;pq_gmtry&gt;      &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt;      &lt;dbl&gt;</span></span>
<span id="cb2-623"><a href="#cb2-623" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1     1 0103000020110F…     1     4    10 27       4       a        &lt;NA&gt;       &lt;NA&gt;  27.4.a    4.a      267336.</span></span>
<span id="cb2-624"><a href="#cb2-624" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2     2 0103000020110F…     2     4    10 27       4       a        &lt;NA&gt;       &lt;NA&gt;  27.4.a    4.a      267336.</span></span>
<span id="cb2-625"><a href="#cb2-625" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3     3 0103000020110F…     3     1     8 27       4       b        &lt;NA&gt;       &lt;NA&gt;  27.4.b    4.b      280957.</span></span>
<span id="cb2-626"><a href="#cb2-626" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4     4 0103000020110F…     4     4    10 27       4       a        &lt;NA&gt;       &lt;NA&gt;  27.4.a    4.a      267336.</span></span>
<span id="cb2-627"><a href="#cb2-627" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5     5 0103000020110F…     5     5    72 27       3       a        &lt;NA&gt;       &lt;NA&gt;  27.3.a    3.a          NA </span></span>
<span id="cb2-628"><a href="#cb2-628" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6     6 0103000020110F…     6     7    40 27       8       a        &lt;NA&gt;       &lt;NA&gt;  27.8.a    8.a       62145.</span></span>
<span id="cb2-629"><a href="#cb2-629" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7     7 0103000020110F…     7     7    40 27       8       a        &lt;NA&gt;       &lt;NA&gt;  27.8.a    8.a       62145.</span></span>
<span id="cb2-630"><a href="#cb2-630" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8     8 0103000020110F…     8     7    40 27       8       a        &lt;NA&gt;       &lt;NA&gt;  27.8.a    8.a       62145.</span></span>
<span id="cb2-631"><a href="#cb2-631" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9     9 0103000020110F…     9    10    46 27       7       e        &lt;NA&gt;       &lt;NA&gt;  27.7.e    7.e       56370.</span></span>
<span id="cb2-632"><a href="#cb2-632" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10    10 0103000020110F…    10     8    42 27       7       b        &lt;NA&gt;       &lt;NA&gt;  27.7.b    7.b       35555.</span></span>
<span id="cb2-633"><a href="#cb2-633" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # … with more rows, and 1 more variable: simplified &lt;chr&gt;</span></span>
<span id="cb2-634"><a href="#cb2-634" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-635"><a href="#cb2-635" aria-hidden="true" tabindex="-1"></a>casestudy <span class="ot">&lt;-</span> <span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;casestudy&quot;</span>))</span>
<span id="cb2-636"><a href="#cb2-636" aria-hidden="true" tabindex="-1"></a>casestudy</span>
<span id="cb2-637"><a href="#cb2-637" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Source:   table&lt;&quot;diadesatlas&quot;.&quot;casestudy&quot;&gt; [?? x 4]</span></span>
<span id="cb2-638"><a href="#cb2-638" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # Database: postgres [ptlambert@citerne.bordeaux.irstea.priv:5432/eurodiad]</span></span>
<span id="cb2-639"><a href="#cb2-639" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   casestudy_id casestudy_name           publishable geom                                                        </span></span>
<span id="cb2-640"><a href="#cb2-640" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          &lt;int&gt; &lt;chr&gt;                    &lt;lgl&gt;       &lt;pq_gmtry&gt;                                                  </span></span>
<span id="cb2-641"><a href="#cb2-641" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1            3 Normand-Breton Gulf      TRUE        0103000020E6100000010000003A010000D08FF885F7A4F0BFCA66C74A9…</span></span>
<span id="cb2-642"><a href="#cb2-642" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2            4 Loire                    TRUE        0106000020E61000000400000001030000000100000005000000E71D48D…</span></span>
<span id="cb2-643"><a href="#cb2-643" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3            6 Gipuzcoan                TRUE        0106000020E610000002000000010300000001000000FA000000F5690FD…</span></span>
<span id="cb2-644"><a href="#cb2-644" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4            1 Waterford Harbour        TRUE        0106000020E610000002000000010300000003000000840200004472DEF…</span></span>
<span id="cb2-645"><a href="#cb2-645" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5            9 Mondego                  TRUE        0106000020E6100000020000000103000000010000006502000090455BF…</span></span>
<span id="cb2-646"><a href="#cb2-646" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6            8 Minho                    TRUE        0103000020E610000001000000B7040000295C2F83AAE61BC0CC7D996F0…</span></span>
<span id="cb2-647"><a href="#cb2-647" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7            2 Tamar-Taff-Frome         TRUE        0106000020E610000003000000010300000001000000CA00000019C5EAD…</span></span>
<span id="cb2-648"><a href="#cb2-648" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8            5 Gironde-Garonne-Dordogne TRUE        0106000020E61000000200000001030000000400000065080000ABC3407…</span></span>
<span id="cb2-649"><a href="#cb2-649" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9            7 Ulla                     TRUE        0103000020E61000000100000066010000AF11015F00D71FC093CDADAA1…</span></span></code></pre></div>
</div>
<div id="create-connection" class="section level3">
<h3>Create connection</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>my_dm <span class="ot">&lt;-</span> <span class="fu">dm_from_src</span>(con, <span class="at">schema =</span> <span class="st">&quot;diadesatlas&quot;</span>, <span class="at">learn_keys =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>my_dm</span></code></pre></div>
</div>
<div id="function-to-collect-data" class="section level3">
<h3>Function to collect data</h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># empty</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dplyr::tbl(con, dbplyr::in_schema(&quot;diadesatlas&quot;, &quot;cices51&quot;)) %&gt;% collect()</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># services ?</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># dplyr::tbl(con, dbplyr::in_schema(&quot;diadesatlas&quot;, &quot;cices&quot;)) %&gt;% collect()</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># services new</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;es_diades&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># geometry of all basin</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;basin_location&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Model results over the years</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;hybrid_model_result&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Abundance of species in a given basin ove the years</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;abundance&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ?</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;climatic_model&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># List of all basins</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;basin&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># List of basin for case_study</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;casestudy&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># List of basins id for case_study</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;casestudy_basin&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># List of ecosystem services</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;ecosystem_service&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;ecosystem_service_new&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co"># List of species</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;species&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span></code></pre></div>
</div>
</div>
<div id="prepare-data-for-home-page" class="section level2">
<h2>Prepare data for Home page</h2>
<div id="prepare-json-files" class="section level3">
<h3>Prepare json files</h3>
<p>Create all json data used on the home page of the app</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of case studies</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>casestudy <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;casestudy&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># List of the corresponding basins</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>casestudy_basin <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;casestudy_basin&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Put them two together</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>cstd <span class="ot">&lt;-</span> <span class="fu">full_join</span>(casestudy, casestudy_basin) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(publishable)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the features for drawing the polygons on the map</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>qry <span class="ot">&lt;-</span> <span class="st">&quot;SELECT ST_Transform(diadesatlas.basin_outlet.simplified_geom, 4326) as geom, basin_id as basin_id FROM diadesatlas.basin_outlet&quot;</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># i then read as an sf object</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>pols <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_read</span>(con, <span class="at">query =</span> qry, <span class="at">geom =</span> <span class="st">&quot;geom&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(basin_id <span class="sc">%in%</span> casestudy_basin<span class="sc">$</span>basin_id) <span class="sc">%&gt;%</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(cstd)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>pols <span class="sc">%&gt;%</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  geojson<span class="sc">::</span><span class="fu">as.geojson</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  geojson<span class="sc">::</span><span class="fu">geo_write</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;inst/casestudy.json&quot;</span>))</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># List of ecosystem services</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>ecosystems <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;ecosystem_service&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>ecosystems <span class="sc">%&gt;%</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(presence <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  jsonlite<span class="sc">::</span><span class="fu">write_json</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;inst/ecosystems.json&quot;</span>))</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Services</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>services <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;v_ecosystemic_services&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>services <span class="sc">%&gt;%</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(category_id, subcategory_id, category_name, subcategory_name) <span class="sc">%&gt;%</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">subcategory_id =</span> <span class="fu">gsub</span>(<span class="st">&quot;99&quot;</span>, <span class="st">&quot;0&quot;</span>, subcategory_id)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    category_id, subcategory_id</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">subcategory_id =</span> <span class="fu">gsub</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;99&quot;</span>, subcategory_id)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>  jsonlite<span class="sc">::</span><span class="fu">write_json</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;inst/services.json&quot;</span>))</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>eco_and_services <span class="ot">&lt;-</span> <span class="fu">full_join</span>(ecosystems, services)</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Species</span></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>species <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">tbl</span>(con, dbplyr<span class="sc">::</span><span class="fu">in_schema</span>(<span class="st">&quot;diadesatlas&quot;</span>, <span class="st">&quot;species&quot;</span>)) <span class="sc">%&gt;%</span> <span class="fu">collect</span>()</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>species <span class="sc">%&gt;%</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species_id <span class="sc">%in%</span> ecosystems<span class="sc">$</span>species_id) <span class="sc">%&gt;%</span></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>  jsonlite<span class="sc">::</span><span class="fu">write_json</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;inst/species.json&quot;</span>))</span></code></pre></div>
</div>
<div id="stop-connection" class="section level3">
<h3>Stop connection</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>DBI<span class="sc">::</span><span class="fu">dbDisconnect</span>(con)</span></code></pre></div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
